import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
from reportlab.lib.pagesizes import letter, inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Image, PageBreak, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
import os
from time import sleep

props = dict(boxstyle='round', facecolor='wheat', alpha=0.5)
good = dict(boxstyle='round', facecolor='palegreen', alpha=0.5)
bad = dict(boxstyle='round', facecolor='lightcoral', alpha=0.5)

###############################################################################################
# Setup Parameters for SBCM Calibration for TOSS (Adjust these Parameters as Needed)
###############################################################################################
year = '2025'

Title = 'Results for SBCM Calibration for TOSS: NSLSII-INS-PRC-005'
CalDate = '1/17/2025'
ReportDate = '1/17/2025'
Engineer = 'Anthony Caracappa'
Technician = 'Mike Capotosto'

ScopeMAN = 'Tektronix'
ScopeMOD = 'MSO64B'
ScopeSN =  'B027138'
ScopeCAL = '12/30/2025'

SourceMAN = 'Rohde & Schwarz'
SourceMOD = 'SMB100B'
SourceSN =  '102801'
SourceCAL = '5/22/2026'

DMM1MAN = 'Keithley'
DMM1MOD = '2100'
DMM1SN = '8020356'
DMM1CAL = '3/20/2025'

DMM2MAN = 'Keithley'
DMM2MOD = '2100'
DMM2SN = '8020357'
DMM2CAL = '3/20/2025'

###############################################################################################
# Manual Measurements
###############################################################################################

# Rectifier Offset Adjutment (mV):
RectOffsetAold = 11.0
RectOffsetAnew = 5.9
RectOffsetBold = 34.8
RectOffsetBnew = 34.1

# Downconverted Frequency Adjustment (MHz):
freqAold = 1.80
freqAnew = 1.80
freqBold = 1.81
freqBnew = 1.81

#Downconverted Output Level for Test RF = 499.68MHz @ -10.0dBm:
TestLevelA = 272.0
TestLevelB = 252.0

# Voltage Supply Measurements:
vp_12 = 11.95
vn_12 = -11.85
vp_5 = 5.01
vn_5 = -4.99


###############################################################################################
# Data Files for SBCM DCCT Calibration for TOSS (Adjust these Parameters as Needed)
###############################################################################################

bscan =    'BandwidthScan.py'             #Python Script to measure the Bandwidth of the SBCM Rectifier Modules
fcurve =   'CharacteristicCurve.py'       #Python Script to measure the Characteristic Curve for each Chain
fscan =    'BeamScan.py'                  #Python Script to measure the Response with Beam from 0 to about 200mA
ftest =    'FunctionalTest.py'            #Python Script to measure when the WDT, COMP, and RELAY Bits turn ON or OFF
frep  =    'ProcessSBCM.py'               #This Python Script generating the Report PDF
fccA =     'SBCM-A_2025_CharCurve.txt'    #File Generated during the Characteristic Curve measurement for Chain A
fccB =     'SBCM-B_2025_CharCurve.txt'    #File Generated during the Characteristic Curve measurement for Chain B
fbm90 =    'SBCM_BeamScanFull_90pctFill_2025.txt'    #File Generated during the Beam Scan for 90% Fill Pattern
fbm20 =    'SBCM_BeamScanFull_20pctFill_2025.txt'    #File Generated during the Beam Scan for 20% Fill Pattern
ftestR90 = 'SBCM_FunctionalTestRising_90pctFill_2025.txt'  #File Generated during Functional Test, 90% Fill, Beam Increasing
ftestF90 = 'SBCM_FunctionalTestFalling_90pctFill_2025.txt' #File Generated during Functional Test, 90% Fill, Beam Decreasing
ftestR20 = 'SBCM_FunctionalTestRising_20pctFill_2025.txt'  #File Generated during Functional Test, 20% Fill, Beam Increasing
ftestF20 = 'SBCM_FunctionalTestFalling_20pctFill_2025.txt' #File Generated during Functional Test, 20% Fill, Beam Decreasing

freport = 'SBCM_Calibration_2025.pdf'   #File Generated by this script for the Calibration Report
if os.path.exists(freport):
    x = input("\n\nFile Exists! Make sure this file is not in use then\nEnter '1' to overwrite or '0' to abort: ")
    if int(x)==1:
        try:
            os.rename(freport,freport)
            print("Available!")
        except OSError as e:
            print("****** ERROR ******\n\n"+freport+" is in use. Please close the file and try again.")
            exit()
    else:
        exit()

###############################################################################################
# Start of Report:
###############################################################################################

doc = SimpleDocTemplate(freport, pagesize=letter, rightMargin=30,leftMargin=30, topMargin=30,bottomMargin=18)
elements = []

tdata = []
tdata.append([Title])
tdata.append(["Procedure Performed on "+CalDate+" by "+Engineer+" and "+Technician])
tdata.append(["Analysis Performed on "+ReportDate+" by "+Engineer])

ta=Table(tdata,6*inch,[0.4*inch,0.22*inch,0.22*inch],style=[
                ('BACKGROUND',(0,0),(0,0),colors.lemonchiffon),
                ('VALIGN',(0,0),(0,0),'MIDDLE'),
                ('LINEABOVE',(0,1),(0,1),2,colors.black),
                ('FONTSIZE', (0,0), (0,0), 12),
                ('GRID',(0,0),(-1,-1),1,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ])

elements.append(ta)

tdata = []
tdata.append(["Test Equipment Used for Calibration","",""])
tdata.append(["Oscilloscope","Manufacturer",ScopeMAN])
tdata.append(["","Model Number",ScopeMOD])
tdata.append(["","Serial Number",ScopeSN])
tdata.append(["","Calibration Expiration",ScopeCAL])
tdata.append(["RF Source","Manufacturer",SourceMAN])
tdata.append(["","Model Number",SourceMOD])
tdata.append(["","Serial Number",SourceSN])
tdata.append(["","Calibration Expiration",SourceCAL])
tdata.append(["DMM1","Manufacturer",DMM1MAN])
tdata.append(["","Model Number",DMM1MOD])
tdata.append(["","Serial Number",DMM1SN])
tdata.append(["","Calibration Expiration",DMM1CAL])
tdata.append(["DMM2","Manufacturer",DMM2MAN])
tdata.append(["","Model Number",DMM2MOD])
tdata.append(["","Serial Number",DMM2SN])
tdata.append(["","Calibration Expiration",DMM2CAL])
tdata.append(["Python Scripts","Bandwidth Scan",bscan])
tdata.append(["","Characteristic Curve",fcurve])
tdata.append(["","Beam Scan",fscan])
tdata.append(["","Report Generation",ftest])
tdata.append(["Output File","DCCT Report",frep])

elements.append(Spacer(width=1,height=0.1*inch))
t0=Table(tdata,2*inch,0.22*inch,style=[
                ('SPAN',(0,0),(2,0)),
                ('BACKGROUND',(0,0),(2,0),colors.lemonchiffon),
                ('LINEABOVE',(0,1),(2,1),2,colors.black),
                ('SPAN',(0,1),(0,4)),
                ('LINEABOVE',(0,5),(2,5),2,colors.black),
                ('SPAN',(0,5),(0,8)),
                ('LINEABOVE',(0,9),(2,9),2,colors.black),
                ('SPAN',(0,9),(0,12)),
                ('LINEABOVE',(0,13),(2,13),2,colors.black),
                ('SPAN',(0,13),(0,16)),
                ('LINEABOVE',(0,17),(2,17),2,colors.black),
                ('SPAN',(0,17),(0,21)),
                ('GRID',(0,0),(-1,-1),1,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('VALIGN',(0,1),(0,21),'MIDDLE'),
                ('BACKGROUND',(0,1),(1,21),colors.lemonchiffon),
                ])

elements.append(t0)

rowH=[]
tdata = []
tdata.append(["Preliminary Settings Adjustments",'',''])
rowH.append(0.4*inch)
tdata.append(["Adjustments made on "+CalDate+" by the CE: "+Engineer,'',''])
rowH.append(0.22*inch)
tdata.append(["Adjustment","Set To:","Status"])
rowH.append(0.22*inch)
tdata.append(["Rectifier Offset A",str(RectOffsetAnew)+'mV',"PASS"])
rowH.append(0.22*inch)
tdata.append(["Rectifier Offset B",str(RectOffsetBnew)+'mV',"PASS"])
rowH.append(0.22*inch)
tdata.append(["Downconverted Frequency A",str(freqAnew)+"MHz","PASS"])
rowH.append(0.22*inch)
tdata.append(["Downconverted Frequency B",str(freqBnew)+"MHz","PASS"])
rowH.append(0.22*inch)
tdata.append(["Measurement","Reading","Status"])
rowH.append(0.22*inch)
tdata.append(["Downconverted Frequency A Level",str(TestLevelA)+"mVpp","PASS"])
rowH.append(0.22*inch)
tdata.append(["Downconverted Frequency B Level",str(TestLevelB)+"mVpp","PASS"])
rowH.append(0.22*inch)

colW = [3*inch,1*inch,1*inch]
elements.append(Spacer(width=1,height=0.1*inch))
ta=Table(tdata,colWidths=colW,rowHeights=rowH,style=[
                ('SPAN',(0,0),(2,0)),
                ('SPAN',(0,1),(2,1)),
                ('BACKGROUND',(0,0),(2,2),colors.lemonchiffon),
                ('BACKGROUND',(0,3),(0,6),colors.lightblue),
                ('BACKGROUND',(0,7),(0,9),colors.lightblue),
                ('BACKGROUND',(2,3),(2,6),colors.palegreen),
                ('BACKGROUND',(2,7),(2,9),colors.palegreen),
                ('VALIGN',(0,0),(0,0),'MIDDLE'),
                ('LINEABOVE',(0,1),(2,1),2,colors.black),
                ('LINEABOVE',(0,2),(2,2),2,colors.black),
                ('LINEABOVE',(0,3),(2,3),2,colors.black),
                ('LINEABOVE',(0,8),(2,8),2,colors.black),
                ('LINEABOVE',(0,7),(2,7),2,colors.black),
                ('BACKGROUND',(0,7),(2,7),colors.lemonchiffon),
                ('FONTSIZE', (0,0), (0,0), 12),
                ('GRID',(0,0),(-1,-1),1,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ])

elements.append(ta)

tdata = []
tdata.append(["Power Supply",""])
tdata.append(["Actual Voltage (V)","Measured Voltage (V)"])
tdata.append(["+12.0 V",str(vp_12)])
tdata.append(["-12.0 V",str(vn_12)])
tdata.append(["+5.0 V",str(vp_5)])
tdata.append(["-5.0 V",str(vn_5)])

elements.append(Spacer(width=1,height=0.1*inch))

ta=Table(tdata,2*inch,0.22*inch,style=[
                ('SPAN',(0,0),(1,0)),
                ('BACKGROUND',(0,0),(1,1),colors.lemonchiffon),
                ('LINEABOVE',(0,1),(1,1),2,colors.black),
                ('LINEABOVE',(0,2),(1,2),2,colors.black),
                ('GRID',(0,0),(-1,-1),1,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('VALIGN',(0,2),(0,5),'MIDDLE'),
                ('BACKGROUND',(0,2),(0,5),colors.lightblue),
                ])

elements.append(ta)

# Create Table for Chain-A Characteristic Curve Measurements:
tdata = []
rowH = []
tdata.append(['SBCM Chain-A Characteristic Curve','','','','file:  '+fccA,'','','',''])
rowH.append(0.22*inch)
tdata.append(['SetPnt\n(mVpp)','Filter\n(mV)','Sigma\n(mV)','SetPnt\n(mVpp)','Filter\n(mV)','Sigma\n(mV)','SetPnt\n(mVpp)','Filter\n(mV)','Sigma\n(mV)'])
rowH.append(0.4*inch)
colW = [0.6*inch,0.8*inch,0.6*inch,0.6*inch,0.8*inch,0.6*inch,0.6*inch,0.8*inch,0.6*inch]

with open(fccA) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]
RF=np.zeros(111)
A =np.zeros(111)
S =np.zeros(111)
for i in range(0,37):
    Z = L[i].split(',')
    RF[i] = 1000*float(Z[0])
    A[i] = float(Z[1])
    S[i] = float(Z[2])
    W = L[i+37].split(',')
    RF[i+37] = 1000*float(W[0])
    A[i+37] = float(W[1])
    S[i+37] = float(W[2])   
    Y = L[i+74].split(',')
    RF[i+74] = 1000*float(Y[0])
    A[i+74] = float(Y[1])
    S[i+74] = float(Y[2]) 
    tdata.append([int(RF[i]),round(A[i],2),round(S[i],4),int(RF[i+37]),round(A[i+37],2),round(S[i+37],4),
                  int(RF[i+74]),round(A[i+74],2),round(S[i+74],4)])
    rowH.append(0.22*inch)
    
tdata.append(['SetPnt:  Rf Source Level Setting in mVpp','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filter:  Average of 16 DMM measurements of the Filter Output from the Rectifier Module','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Sigma:  The Standard Deviation of the 16 DMM Filter measurements','','','','','','','',''])
rowH.append(0.22*inch)

elements.append(PageBreak())     
t2=Table(tdata,colWidths=colW,rowHeights=rowH,style=[
                ('SPAN',(0,0),(3,0)),
                ('SPAN',(4,0),(8,0)),
                ('BACKGROUND',(0,0),(8,0),colors.lemonchiffon),
                ('BACKGROUND',(0,1),(0,38),colors.lightblue),
                ('BACKGROUND',(3,1),(3,38),colors.lightblue),
                ('BACKGROUND',(6,1),(6,38),colors.lightblue),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('LINEABOVE',(0,1),(8,1),2,colors.black),
                ('LINEABOVE',(0,2),(8,2),1.5,colors.black),
                ('LINEBEFORE',(1,1),(1,38),1.5,colors.black),
                ('LINEBEFORE',(3,1),(3,38),2,colors.black),
                ('LINEBEFORE',(4,0),(4,38),1.5,colors.black),
                ('LINEBEFORE',(6,1),(6,38),2,colors.black),
                ('LINEBEFORE',(7,1),(7,38),1.5,colors.black),
                ('SPAN',(0,39),(8,39)),
                ('SPAN',(0,40),(8,40)),
                ('SPAN',(0,41),(8,41)),
                ('LINEABOVE',(0,39),(8,39),1.5,colors.black),
                ('BACKGROUND',(0,39),(8,41),colors.lemonchiffon),
                ])

elements.append(t2)

# Analyze Data Chain-A Characteristic Curve:

fa,ax = plt.subplots(2,1,figsize=(6,9))

m,b = np.polyfit(RF[0:100],A[0:100],1)
correlation_matrix = np.corrcoef(RF[0:100],A[0:100])
p = correlation_matrix[0, 1]

Acalc=[]
for i in range(0,100):
    Acalc.append(m*RF[i]+b)

ax[0].plot(RF,A,'-o',markersize=5,linewidth=3,label='Data')
ax[0].plot(RF[0:100],Acalc,'-o',markersize=2,linewidth=1,label='Fit')
ax[0].set_title('SBCM Chain A Characteristic Curve')
ax[0].grid(True)
ax[0].set_xlabel('RF Level @ 499.68MHz (mV)')
ax[0].set_ylabel('Average Rectifier Filter Output (mV)')
ax[0].text(0.05, 0.95, "Slope: "+str(round(m,5))+"mVa/mVrf",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.86, "Intercept: "+str(round(b,4))+"mVa",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.77, "Correlation: "+str(round(p,6)),transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)  
if(p>0.99):
    ax[0].text(0.05, 0.68, "Correlation>0.99?: PASS",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[0].text(0.05, 0.68, "Correlation>0.99?: FAIL",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
mess = 'Each point is the average of the 16\nconsecutive measurements taken at\n'
mess = mess+'each RF Level setting.  The fit is\nperformed for RF settings between\n5mVpp and 500mVpp'
ax[0].text(0.44, 0.44,mess,transform=ax[0].transAxes, fontsize=10,verticalalignment='top', bbox=props)
ax[0].legend(loc='lower right')

ax[1].plot(RF,S,'-o',markersize=3,linewidth=1,label='Data')
ax[1].grid(True)
ax[1].set_xlabel('RF Level @ 499.68MHz (mV)')
ax[1].set_ylabel('Sigma for Filter Output Average (mV)')
mess = 'Each point is the standard\ndeviation of the 16 measurements\n'
mess = mess+'used to calculate the average\nFilter Output for each\nRF level setting shown above'
ax[1].text(0.01, 0.98,mess,transform=ax[1].transAxes, fontsize=10,verticalalignment='top', bbox=props)
if(max(S)<4.0):
    ax[1].text(0.05, 0.68, "max(Sigma)<4.0?: PASS",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[1].text(0.05, 0.68, "max(Sigma)<4.0?: FAIL",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
plt.pause(0.1)
fa.savefig('SBCM_CharCurveA_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_CharCurveA_'+year+'.png',6*inch,9*inch)
elements.append(im)

# Create Table for Chain-B Characteristic Curve Measurements:
tdata = []
rowH = []
tdata.append(['SBCM Chain-B Characteristic Curve','','','','file:  '+fccB,'','','',''])
rowH.append(0.22*inch)
tdata.append(['SetPnt\n(mV)','Filter\n(mV)','Sigma\n(mV)','SetPnt\n(mV)','Filter\n(mV)','Sigma\n(mV)','SetPnt\n(mV)','Filter\n(mV)','Sigma\n(mV)'])
rowH.append(0.4*inch)
colW = [0.6*inch,0.8*inch,0.6*inch,0.6*inch,0.8*inch,0.6*inch,0.6*inch,0.8*inch,0.6*inch]

with open(fccB) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]
RF=np.zeros(111)
B =np.zeros(111)
S =np.zeros(111)
for i in range(0,37):
    Z = L[i].split(',')
    RF[i] = 1000*float(Z[0])
    B[i] = float(Z[1])
    S[i] = float(Z[2])
    W = L[i+37].split(',')
    RF[i+37] = 1000*float(W[0])
    B[i+37] = float(W[1])
    S[i+37] = float(W[2])   
    Y = L[i+74].split(',')
    RF[i+74] = 1000*float(Y[0])
    B[i+74] = float(Y[1])
    S[i+74] = float(Y[2]) 
    tdata.append([int(RF[i]),round(B[i],2),round(S[i],4),int(RF[i+37]),round(B[i+37],2),round(S[i+37],4),
                  int(RF[i+74]),round(B[i+74],2),round(S[i+74],4)])
    rowH.append(0.22*inch)

tdata.append(['SetPnt:  Rf Source Level Setting in mVpp','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filter:  Average of 16 DMM measurements of the Filter Output from the Rectifier Module','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Sigma:  The Standard Deviation of the 16 DMM Filter measurements','','','','','','','',''])
rowH.append(0.22*inch)

elements.append(PageBreak())     
t2=Table(tdata,colWidths=colW,rowHeights=rowH,style=[
                ('SPAN',(0,0),(3,0)),
                ('SPAN',(4,0),(8,0)),
                ('BACKGROUND',(0,0),(8,0),colors.lemonchiffon),
                ('BACKGROUND',(0,1),(0,38),colors.lightblue),
                ('BACKGROUND',(3,1),(3,38),colors.lightblue),
                ('BACKGROUND',(6,1),(6,38),colors.lightblue),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('LINEABOVE',(0,1),(8,1),2,colors.black),
                ('LINEABOVE',(0,2),(8,2),1.5,colors.black),
                ('LINEBEFORE',(1,1),(1,38),1.5,colors.black),
                ('LINEBEFORE',(3,1),(3,38),2,colors.black),
                ('LINEBEFORE',(4,0),(4,38),1.5,colors.black),
                ('LINEBEFORE',(6,1),(6,38),2,colors.black),
                ('LINEBEFORE',(7,1),(7,38),1.5,colors.black),
                ('SPAN',(0,39),(8,39)),
                ('SPAN',(0,40),(8,40)),
                ('SPAN',(0,41),(8,41)),
                ('LINEABOVE',(0,39),(8,39),1.5,colors.black),
                ('BACKGROUND',(0,39),(8,41),colors.lemonchiffon),
                ])

elements.append(t2)

# Analyze Data Chain-B Characteristic Curve:

fa,ax = plt.subplots(2,1,figsize=(6,9))

m,b = np.polyfit(RF[0:100],B[0:100],1)
correlation_matrix = np.corrcoef(RF[0:100],B[0:100])
p = correlation_matrix[0, 1]

Bcalc=[]
for i in range(0,100):
    Bcalc.append(m*RF[i]+b)

ax[0].plot(RF,B,'-o',markersize=5,linewidth=3,label='Data')
ax[0].plot(RF[0:100],Bcalc,'-o',markersize=2,linewidth=1,label='Fit')
ax[0].set_title('SBCM Chain B Characteristic Curve')
ax[0].grid(True)
ax[0].set_xlabel('RF Level @ 499.68MHz (mV)')
ax[0].set_ylabel('Average Rectifier Filter Output (mV)')
ax[0].text(0.05, 0.95, "Slope: "+str(round(m,5))+"mVa/mVrf",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.86, "Intercept: "+str(round(b,4))+"mVa",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.77, "Correlation: "+str(round(p,6)),transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)  
if(p>0.99):
    ax[0].text(0.05, 0.68, "Correlation>0.99?: PASS",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[0].text(0.05, 0.68, "Correlation>0.99?: FAIL",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
mess = 'Each point is the average of the 16\nconsecutive measurements taken at\n'
mess = mess+'each RF Level setting.  The fit is\nperformed for RF settings between\n5mVpp and 500mVpp'
ax[0].text(0.44, 0.44,mess,transform=ax[0].transAxes, fontsize=10,verticalalignment='top', bbox=props)
ax[0].legend(loc='lower right')
ax[1].plot(RF,S,'-o',markersize=3,linewidth=1,label='Data')
ax[1].grid(True)
ax[1].set_xlabel('RF Level @ 499.68MHz (mV)')
ax[1].set_ylabel('Sigma for Filter Output Average (mV)')
mess = 'Each point is the standard\ndeviation of the 16 measurements\n'
mess = mess+'used to calculate the average\nFilter Output for each\nRF level setting shown above'
ax[1].text(0.01, 0.98,mess,transform=ax[1].transAxes, fontsize=10,verticalalignment='top', bbox=props)
if(max(S)<4.0):
    ax[1].text(0.05, 0.68, "max(Sigma)<4.0?: PASS",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[1].text(0.05, 0.68, "max(Sigma)<4.0?: FAIL",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
plt.pause(0.1)
fa.savefig('SBCM_CharCurveB_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_CharCurveB_'+year+'.png',6*inch,9*inch)
elements.append(im)
        
# Create Table for Beam Scan with 90% Fill Pattern:
tdata = []
rowH = []
tdata.append(['SBCM Beam Scan with 90% Fill','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['file:  '+fbm90,'','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['SR Beam\nPLC(mA)','Chain-A\nFilter(mV)','Chain-B\nFilter(mV)',
              'SR Beam\nPLC(mA)','Chain-A\nFilter(mV)','Chain-B\nFilter(mV)',
              'SR Beam\nPLC(mA)','Chain-A\nFilter(mV)','Chain-B\nFilter(mV)',])
rowH.append(0.4*inch)

with open(fbm90) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]

N = int(len(L))

target = 81.0
A=[]
B=[]
I=[]
i=0
while(target>27):
    Z = L[i].split(',')
    i=i+1
    if(float(Z[2])<=target):
        A.append(float(Z[0]))
        B.append(float(Z[1]))
        I.append(float(Z[2]))
        target = target - 0.5
        
N = int(len(A)/3)           
for i in range(0,N):
    dat = [str(round(I[i],2)),str(round(A[i],2)),str(round(B[i],2)),
           str(round(I[N+i],2)),str(round(A[N+i],2)),str(round(B[N+i],2)),
           str(round(I[2*N+i],2)),str(round(A[2*N+i],2)),str(round(B[2*N+i],2))]
    tdata.append(dat)
    rowH.append(0.22*inch)

tdata.append(['SR Beam PLC:  EPS PLC Measurement of Stored Beam Intensity','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filter ChainA:  DMM measurement of Output from Chain-A Rectifier Module','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filter ChainB:  DMM measurement of Output from Chain-B Rectifier Module','','','','','','','',''])
rowH.append(0.22*inch)

elements.append(PageBreak())     
t2=Table(tdata,0.75*inch,rowHeights=rowH,style=[
                ('SPAN',(0,0),(8,0)),
                ('SPAN',(0,1),(8,1)),
                ('BACKGROUND',(0,0),(8,1),colors.lemonchiffon),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('LINEABOVE',(0,1),(8,1),2,colors.black),
                ('LINEABOVE',(0,2),(8,2),2,colors.black),
                ('LINEABOVE',(0,3),(8,3),2,colors.black),
                ('LINEBEFORE',(3,1),(3,38),2,colors.black),
                ('LINEBEFORE',(6,1),(6,38),2,colors.black),
                ('LINEABOVE',(0,39),(8,39),2,colors.black),
                ('SPAN',(0,39),(8,39)),
                ('SPAN',(0,40),(8,40)),
                ('SPAN',(0,41),(8,41)),
                ('BACKGROUND',(0,39),(8,41),colors.lemonchiffon),
                ])

elements.append(t2)

# Analyze Data for 90% Fill Pattern Beam Scan:

fa,ax = plt.subplots(2,1,figsize=(6,9))

m,b = np.polyfit(A,I,1)
correlation_matrix = np.corrcoef(A,I)
p = correlation_matrix[0, 1]

Icalc=[]
for i in range(0,len(A)):
    Icalc.append(m*A[i]+b)

ax[0].plot(A,I,'-o',markersize=5,linewidth=3,label='Data')
ax[0].plot(A,Icalc,'-o',markersize=2,linewidth=1,label='Fit')
ax[0].set_title('EPS PLC Beam Current vs Filter Voltage for 90% Fill Pattern')
ax[0].grid(True)
ax[0].set_xlabel('Chain-A Filter Measurement (mV)')
ax[0].set_ylabel('EPS PLC Beam Current Measurement (mA)')
ax[0].text(0.05, 0.95, "Slope: "+str(round(m,5))+"mA/mV",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.86, "Intercept: "+str(round(b,4))+"mA",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.77, "Correlation: "+str(round(p,6)),transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)  
if(p>0.99):
    ax[0].text(0.05, 0.68, "Correlation>0.99?: PASS",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[0].text(0.05, 0.68, "Correlation>0.99?: FAIL",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
ymin,ymax=ax[0].get_ylim()
xmin,xmax=ax[0].get_xlim()
Vtoss = 1010  #Determined by Engineer for Chain A
Itoss = m*Vtoss + b #mA , determined by Fit
ax[0].autoscale(enable=False,axis='both')
ax[0].plot([xmin,Vtoss,Vtoss],[Itoss,Itoss,ymin],'--o',color='black',markersize=6,markerfacecolor='red',
           markeredgecolor='black',linewidth=2,label='TOSS')
ax[0].text(0.62, 0.45, "90% Fill Pattern\nThreshold: "+str(Vtoss)+'mV\nI(TOSS): '+str(round(Itoss,2))+'mA',transform=ax[0].transAxes,
           fontsize=12,verticalalignment='top', bbox=props) 
ax[0].legend(loc='lower right')

m,b = np.polyfit(B,I,1)
correlation_matrix = np.corrcoef(B,I)
p = correlation_matrix[0, 1]

Icalc=[]
for i in range(0,len(B)):
    Icalc.append(m*B[i]+b)
    
ax[1].plot(B,I,'-o',markersize=5,linewidth=3,label='Data')
ax[1].plot(B,Icalc,'-o',markersize=2,linewidth=1,label='Fit')
ax[1].grid(True)
ax[1].set_xlabel('Chain-B Filter Measurement (mV)')
ax[1].set_ylabel('EPS PLC Beam Current Measurement (mA)')
ax[1].text(0.05, 0.95, "Slope: "+str(round(m,5))+"mA/mV",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[1].text(0.05, 0.86, "Intercept: "+str(round(b,4))+"mA",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[1].text(0.05, 0.77, "Correlation: "+str(round(p,6)),transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=props)   
if(p>0.99):
    ax[1].text(0.05, 0.68, "Correlation>0.99?: PASS",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[1].text(0.05, 0.68, "Correlation>0.99?: FAIL",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
ymin,ymax=ax[1].get_ylim()
xmin,xmax=ax[1].get_xlim()
Vtoss = 1010  #Determined by Engineer for Chain B
Itoss = m*Vtoss + b #mA , determined by Fit
ax[1].autoscale(enable=False,axis='both')
ax[1].plot([xmin,Vtoss,Vtoss],[Itoss,Itoss,ymin],'--o',color='black',markersize=6,markerfacecolor='red',
           markeredgecolor='black',linewidth=2,label='TOSS')
ax[1].text(0.62, 0.45, "90% Fill Pattern\nThreshold: "+str(Vtoss)+'mV\nI(TOSS): '+str(round(Itoss,2))+'mA',transform=ax[1].transAxes,
           fontsize=12,verticalalignment='top', bbox=props) 
ax[1].legend(loc='lower right')
plt.pause(0.1)
fa.savefig('SBCM_90pctFill_BeamScan_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_90pctFill_BeamScan_'+year+'.png',6*inch,9*inch)
elements.append(im)

# Create Table for Beam Scan with 20% Fill Pattern:
tdata = []
rowH = []
tdata.append(['SBCM Beam Scan with 20% Fill','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['file:  '+fbm20,'','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['SR Beam\nPLC(mA)','Chain-A\nFilter(mV)','Chain-B\nFilter(mV)',
              'SR Beam\nPLC(mA)','Chain-A\nFilter(mV)','Chain-B\nFilter(mV)',
              'SR Beam\nPLC(mA)','Chain-A\nFilter(mV)','Chain-B\nFilter(mV)',])
rowH.append(0.4*inch)

with open(fbm20) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]

N = int(len(L))

target = 77.0
A=[]
B=[]
I=[]
i=0
while(target>23):
    Z = L[i].split(',')
    i=i+1
    if(float(Z[2])<=target):
        A.append(float(Z[0]))
        B.append(float(Z[1]))
        I.append(float(Z[2]))
        target = target - 0.5
N = int(len(A)/3)           
for i in range(0,N):
    dat = [str(round(I[i],2)),str(round(A[i],2)),str(round(B[i],2)),
           str(round(I[N+i],2)),str(round(A[N+i],2)),str(round(B[N+i],2)),
           str(round(I[2*N+i],2)),str(round(A[2*N+i],2)),str(round(B[2*N+i],2))]
    tdata.append(dat)
    rowH.append(0.22*inch)

tdata.append(['SR Beam PLC:  EPS PLC Measurement of Stored Beam Intensity','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filter ChainA:  DMM measurement of Output from Chain-A Rectifier Module','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filter ChainB:  DMM measurement of Output from Chain-B Rectifier Module','','','','','','','',''])
rowH.append(0.22*inch)


elements.append(PageBreak())     
t2=Table(tdata,0.75*inch,rowHeights=rowH,style=[
                ('SPAN',(0,0),(8,0)),
                ('SPAN',(0,1),(8,1)),
                ('BACKGROUND',(0,0),(8,1),colors.lemonchiffon),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('LINEABOVE',(0,1),(8,1),2,colors.black),
                ('LINEABOVE',(0,2),(8,2),2,colors.black),
                ('LINEABOVE',(0,3),(8,3),2,colors.black),
                ('LINEBEFORE',(3,1),(3,38),2,colors.black),
                ('LINEBEFORE',(6,1),(6,38),2,colors.black),
                ('LINEABOVE',(0,39),(8,39),2,colors.black),
                ('SPAN',(0,39),(8,39)),
                ('SPAN',(0,40),(8,40)),
                ('SPAN',(0,41),(8,41)),
                ('BACKGROUND',(0,39),(8,41),colors.lemonchiffon),
                ])
elements.append(t2)

# Analyze Data for 20% Fill Pattern Beam Scan:

fa,ax = plt.subplots(2,1,figsize=(6,9))

m,b = np.polyfit(A,I,1)
correlation_matrix = np.corrcoef(A,I)
p = correlation_matrix[0, 1]

Icalc=[]
for i in range(0,len(A)):
    Icalc.append(m*A[i]+b)

ax[0].plot(A,I,'-o',markersize=5,linewidth=3,label='Data')
ax[0].plot(A,Icalc,'-o',markersize=2,linewidth=1,label='Fit')
ax[0].set_title('EPS PLC Beam Current vs Filter Voltage for 20% Fill Pattern')
ax[0].grid(True)
ax[0].set_xlabel('Chain-A Filter Measurement (mV)')
ax[0].set_ylabel('EPS PLC Beam Current Measurement (mA)')
ax[0].text(0.05, 0.95, "Slope: "+str(round(m,5))+"mA/mV",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.86, "Intercept: "+str(round(b,4))+"mA",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.77, "Correlation: "+str(round(p,6)),transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)  
if(p>0.99):
    ax[0].text(0.05, 0.68, "Correlation>0.99?: PASS",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[0].text(0.05, 0.68, "Correlation>0.99?: FAIL",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
ymin,ymax=ax[0].get_ylim()
xmin,xmax=ax[0].get_xlim()
Vtoss = 1010  #Determined by Engineer for Chain A
Itoss = m*Vtoss + b #mA , determined by Fit
ax[0].autoscale(enable=False,axis='both')
ax[0].plot([xmin,Vtoss,Vtoss],[Itoss,Itoss,ymin],'--o',color='black',markersize=6,markerfacecolor='red',
           markeredgecolor='black',linewidth=2,label='TOSS')
ax[0].text(0.62, 0.45, "20% Fill Pattern\nThreshold: "+str(Vtoss)+'mV\nI(TOSS): '+str(round(Itoss,2))+'mA',transform=ax[0].transAxes,
           fontsize=12,verticalalignment='top', bbox=props) 
ax[0].legend(loc='lower right')

m,b = np.polyfit(B,I,1)
correlation_matrix = np.corrcoef(B,I)
p = correlation_matrix[0, 1]

Icalc=[]
for i in range(0,len(B)):
    Icalc.append(m*B[i]+b)
    
ax[1].plot(B,I,'-o',markersize=5,linewidth=3,label='Data')
ax[1].plot(B,Icalc,'-o',markersize=2,linewidth=1,label='Fit')
ax[1].grid(True)
ax[1].set_xlabel('Chain-B Filter Measurement (mV)')
ax[1].set_ylabel('EPS PLC Beam Current Measurement (mA)')
ax[1].text(0.05, 0.95, "Slope: "+str(round(m,5))+"mA/mV",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[1].text(0.05, 0.86, "Intercept: "+str(round(b,4))+"mA",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[1].text(0.05, 0.77, "Correlation: "+str(round(p,6)),transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=props)   
if(p>0.99):
    ax[1].text(0.05, 0.68, "Correlation>0.99?: PASS",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[1].text(0.05, 0.68, "Correlation>0.99?: FAIL",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
ymin,ymax=ax[1].get_ylim()
xmin,xmax=ax[1].get_xlim()
Vtoss = 1010  #Determined by Engineer for Chain B
Itoss = m*Vtoss + b #mA , determined by Fit
ax[1].autoscale(enable=False,axis='both')
ax[1].plot([xmin,Vtoss,Vtoss],[Itoss,Itoss,ymin],'--o',color='black',markersize=6,markerfacecolor='red',
           markeredgecolor='black',linewidth=2,label='TOSS')
ax[1].text(0.62, 0.45, "20% Fill Pattern\nThreshold: "+str(Vtoss)+'mV\nI(TOSS): '+str(round(Itoss,2))+'mA',transform=ax[1].transAxes,
           fontsize=12,verticalalignment='top', bbox=props) 
ax[1].legend(loc='lower right')
plt.pause(0.1)
fa.savefig('SBCM_20pctFill_BeamScan_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_20pctFill_BeamScan_'+year+'.png',6*inch,9*inch)
elements.append(im)

tdata=[]
tdata.append(['Based on the data shown above the following changes were made:'])
tdata.append(['I(TOSS) = 54mA for a 20% Fill Pattern'])
tdata.append(['Chain-A Threshold set to 1010mV'])
tdata.append(['Chain-B Threshold set to 1010mV'])
   
t2=Table(tdata,5*inch,0.22*inch,style=[
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('BACKGROUND',(0,0),(-1,-1),colors.lemonchiffon),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ])
elements.append(t2)

# Create Table for Functional Test with 20% Fill Pattern and Beam Increasing:
tdata = []
rowH = []
tdata.append(['SBCM Functional Scan with 20% Fill and Increasing Beam','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['file:  '+fbm20,'','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'
              ,'','Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'])
rowH.append(0.4*inch)

with open(ftestR20) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]
N = int(len(L))
WDTA20R=[0,0]
COMA20R=[0,0]
RELA20R=[0,0]
WDTB20R=[0,0]
COMB20R=[0,0]
RELB20R=[0,0]
AW=[]
BW=[]
IW=[]
WAW=[]
CAW=[]
RAW=[]
WBW=[]
CBW=[]
RBW=[]
target = 0.0
for i in range(0,N):
    tag=0
    Z = L[i].split(',')
    I=float(Z[0])
    A=float(Z[1])
    B=float(Z[2])
    WA=int(Z[3])
    CA=int(Z[4])
    RA=int(Z[5])
    WB=int(Z[6])
    CB=int(Z[7])
    RB=int(Z[8])
    if(I > target):
        tag=1
        target = target + 1
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTA20R[0]==0 and WA==1 and tag==0):
        tag = 1
        WDTA20R[0] = I
        WDTA20R[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTB20R[0]==0 and WB==1 and tag==0):
        tag = 1
        WDTB20R[0] = I
        WDTB20R[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMA20R[0]==0 and CA==2 and tag==0):
        tag = 1
        COMA20R[0] = I
        COMA20R[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMB20R[0]==0 and CB==2 and tag==0):
        tag = 1
        COMB20R[0] = I
        COMB20R[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELA20R[0]==0 and RA==3 and tag==0):
        tag = 1
        RELA20R[0] = I
        RELA20R[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELB20R[0]==0 and RB==3 and tag==0):
        tag = 1
        RELB20R[0] = I
        RELB20R[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)

N = int(len(AW)/2)           
for i in range(0,N):
    dat = [str(round(IW[i],2)),str(round(AW[i],2)),str(WAW[i])+','+str(CAW[i])+','+str(RAW[i]),
           str(round(BW[i],2)),str(WBW[i])+','+str(CBW[i])+','+str(RBW[i]),'',
           str(round(IW[N+i],2)),str(round(AW[N+i],2)),str(WAW[N+i])+','+str(CAW[N+i])+','+str(RAW[N+i]),
           str(round(BW[N+i],2)),str(WBW[N+i])+','+str(CBW[N+i])+','+str(RBW[N+i])]                                                                                    
    tdata.append(dat)
    rowH.append(0.22*inch)  
tdata.append(["Beam: Storage Ring Beam as Measured by the EPS PLC Chassis in mA"])
rowH.append(0.22*inch)
tdata.append(["Filt-A: Chain-A Rectifier Module Filter Output Measured by the Keithley 2100 in mV"])
rowH.append(0.22*inch)
tdata.append(["Bits-A: Chain-A State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC"])
rowH.append(0.22*inch)
tdata.append(["Filt-B: Chain-B Rectifier Module Filter Output Measured by the Keithley 2100 in mV"])
rowH.append(0.22*inch)
tdata.append(["Bits-B: Chain-B State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC"])
rowH.append(0.22*inch)
colW = [0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch,0.07*inch,0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch]
elements.append(PageBreak())     
t2=Table(tdata,colWidths=colW,rowHeights=rowH,style=[
                ('SPAN',(0,0),(10,0)),
                ('SPAN',(0,1),(10,1)),
                ('BACKGROUND',(0,0),(10,1),colors.lemonchiffon),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('LINEABOVE',(0,1),(10,1),2,colors.black),
                ('LINEABOVE',(0,2),(10,2),2,colors.black),
                ('LINEABOVE',(0,3),(10,3),2,colors.black),
                ('LINEABOVE',(0,36),(10,36),2,colors.black),
                ('BACKGROUND',(0,36),(10,40),colors.lemonchiffon),
                ('SPAN',(0,36),(10,36)),
                ('SPAN',(0,37),(10,37)),
                ('SPAN',(0,38),(10,38)),
                ('SPAN',(0,39),(10,39)),
                ('SPAN',(0,40),(10,40)),
                ])
elements.append(t2)

fa,ax = plt.subplots(2,1,figsize=(7,9))
ax02 = ax[0].twinx()
ax12 = ax[1].twinx()

ax[0].plot(IW,'-o',color='blue')
ax[0].grid(True)
ax[0].set_xlabel("Time (AU)")
ax[0].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[0].set_title("SBCM-A 20% Fill Functional Test")
ax[0].tick_params(axis='y', labelcolor='blue')
ax02.plot(WAW,'-o',color='red')
ax02.plot(CAW,'-o',color='green')
ax02.plot(RAW,'-o',color='black')
ax02.set_ylabel("SBCM-A Status Bits",color='black')
ax02.set_yticks([0,1,2,3,4,5])
ax02.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT ON: Beam="+str(round(WDTA20R[0],2))+"mA  SBCM="+str(round(WDTA20R[1],1))+"mV"
ax02.text(0.05, 0.96,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP ON: Beam="+str(round(COMA20R[0],2))+"mA  SBCM="+str(round(COMA20R[1],1))+"mV"
ax02.text(0.05, 0.89,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELA20R[0]<51.3 or RELA20R[0]>56.7):
    line = "RELAY ON: Beam="+str(round(RELA20R[0],2))+"mA  SBCM="+str(round(RELA20R[1],1))+"mV\n"
    line = line+"Beam within 5% of I(TOSS)=54mA:\n51.3 < RELAY ON Beam < 56.7 ? FAIL"
    ax02.text(0.05, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY ON: Beam="+str(round(RELA20R[0],2))+"mA  SBCM="+str(round(RELA20R[1],1))+"mV\n"
    line = line+"Beam within 5% of I(TOSS)=54mA:\n51.3 < RELAY ON Beam < 56.7 ? PASS"
    ax02.text(0.05, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=good)
ax[1].plot(IW,'-o',color='blue')
ax[1].grid(True)
ax[1].set_xlabel("Time (AU)")
ax[1].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[1].tick_params(axis='y', labelcolor='blue')
ax12.plot(WBW,'-o',color='red')
ax12.plot(CBW,'-o',color='green')
ax12.plot(RBW,'-o',color='black')
ax12.set_ylabel("SBCM-B Status Bits",color='black')
ax[1].set_title("SBCM-B 20% Fill Functional Test")
ax12.set_yticks([0,1,2,3,4,5])
ax12.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT ON: Beam="+str(round(WDTB20R[0],2))+"mA  SBCM="+str(round(WDTB20R[1],1))+"mV"
ax12.text(0.05, 0.96,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP ON: Beam="+str(round(COMB20R[0],2))+"mA  SBCM="+str(round(COMB20R[1],1))+"mV"
ax12.text(0.05, 0.89,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELB20R[0]<51.3 or RELB20R[0]>56.7):
    line = "RELAY ON: Beam="+str(round(RELB20R[0],2))+"mA  SBCM="+str(round(RELB20R[1],1))+"mV\n"
    line = line+"Beam within 5% of I(TOSS)=54mA:\n51.3 < RELAY ON Beam < 56.7 ? FAIL"
    ax12.text(0.05, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY ON: Beam="+str(round(RELB20R[0],2))+"mA  SBCM="+str(round(RELB20R[1],1))+"mV\n"
    line = line+"Beam within 5% of I(TOSS)=54mA:\n51.3 < RELAY ON Beam < 56.7 ? PASS"
    ax12.text(0.05, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=good)

plt.tight_layout()
plt.pause(0.1)
plt.pause(0.1)
fa.savefig('SBCM_20pctFillBeamRisingFunctTest_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_20pctFillBeamRisingFunctTest_'+year+'.png',7*inch,9*inch)
elements.append(im)

# Create Table for Functional Test with 20% Fill Pattern and Beam Decreasing:
tdata = []
rowH = []
tdata.append(['SBCM Functional Scan with 20% Fill and Decreasing Beam','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['file:  '+ftestF20,'','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'
              ,'','Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'])
rowH.append(0.4*inch)

with open(ftestF20) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]
N = int(len(L))
WDTA20F=[0,0]
COMA20F=[0,0]
RELA20F=[0,0]
WDTB20F=[0,0]
COMB20F=[0,0]
RELB20F=[0,0]
AW=[]
BW=[]
IW=[]
WAW=[]
CAW=[]
RAW=[]
WBW=[]
CBW=[]
RBW=[]
target = 60.0
for i in range(0,N):
    Z = L[i].split(',')
    I=float(Z[0])
    A=float(Z[1])
    B=float(Z[2])
    WA=int(Z[3])
    CA=int(Z[4])
    RA=int(Z[5])
    WB=int(Z[6])
    CB=int(Z[7])
    RB=int(Z[8])
    if(I < target):
        if((target-1)<I):
            target = target - 1
        else:
            target = I - 1
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTA20F[0]==0 and WA==0):
        WDTA20F[0] = I
        WDTA20F[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTB20F[0]==0 and WB==0):
        WDTB20F[0] = I
        WDTB20F[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMA20F[0]==0 and CA==0):
        COMA20F[0] = I
        COMA20F[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMB20F[0]==0 and CB==0):
        COMB20F[0] = I
        COMB20F[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELA20F[0]==0 and RA==0):
        RELA20F[0] = I
        RELA20F[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELB20F[0]==0 and RB==0):
        RELB20F[0] = I
        RELB20F[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)

N = int(len(AW)/2)           
for i in range(0,N):
    dat = [str(round(IW[i],2)),str(round(AW[i],2)),str(WAW[i])+','+str(CAW[i])+','+str(RAW[i]),
           str(round(BW[i],2)),str(WBW[i])+','+str(CBW[i])+','+str(RBW[i]),'',
           str(round(IW[N+i],2)),str(round(AW[N+i],2)),str(WAW[N+i])+','+str(CAW[N+i])+','+str(RAW[N+i]),
           str(round(BW[N+i],2)),str(WBW[N+i])+','+str(CBW[N+i])+','+str(RBW[N+i])]                                                                                    
    tdata.append(dat)
    rowH.append(0.22*inch)  
tdata.append(["Beam: Storage Ring Beam as Measured by the EPS PLC Chassis in mA"])
rowH.append(0.22*inch)
tdata.append(["Filt-A: Chain-A Rectifier Module Filter Output Measured by the Keithley 2100 in mV"])
rowH.append(0.22*inch)
tdata.append(["Bits-A: Chain-A State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC"])
rowH.append(0.22*inch)
tdata.append(["Filt-B: Chain-B Rectifier Module Filter Output Measured by the Keithley 2100 in mV"])
rowH.append(0.22*inch)
tdata.append(["Bits-B: Chain-B State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC"])
rowH.append(0.22*inch)
colW = [0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch,0.07*inch,0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch]
elements.append(PageBreak())     
t2=Table(tdata,colWidths=colW,rowHeights=rowH,style=[
                ('SPAN',(0,0),(10,0)),
                ('SPAN',(0,1),(10,1)),
                ('BACKGROUND',(0,0),(10,1),colors.lemonchiffon),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('LINEABOVE',(0,1),(10,1),2,colors.black),
                ('LINEABOVE',(0,2),(10,2),2,colors.black),
                ('LINEABOVE',(0,3),(10,3),2,colors.black),
                ('LINEABOVE',(0,36),(10,36),2,colors.black),
                ('BACKGROUND',(0,36),(10,40),colors.lemonchiffon),
                ('SPAN',(0,36),(10,36)),
                ('SPAN',(0,37),(10,37)),
                ('SPAN',(0,38),(10,38)),
                ('SPAN',(0,39),(10,39)),
                ('SPAN',(0,40),(10,40)),
                ])
elements.append(t2)

fa,ax = plt.subplots(2,1,figsize=(7,9))
ax02 = ax[0].twinx()
ax12 = ax[1].twinx()

ax[0].plot(IW,'-o',color='blue')
ax[0].grid(True)
ax[0].set_xlabel("Time (AU)")
ax[0].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[0].set_title("SBCM-A 20% Fill Functional Test")
ax[0].tick_params(axis='y', labelcolor='blue')
ax02.plot(WAW,'-o',color='red')
ax02.plot(CAW,'-o',color='green')
ax02.plot(RAW,'-o',color='black')
ax02.set_ylabel("SBCM-A Status Bits",color='black')
ax02.set_yticks([0,1,2,3,4,5])
ax02.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT OFF: Beam="+str(round(WDTA20F[0],2))+"mA  SBCM="+str(round(WDTA20F[1],1))+"mV"
ax02.text(0.35, 0.96,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP OFF: Beam="+str(round(COMA20F[0],2))+"mA  SBCM="+str(round(COMA20F[1],1))+"mV"
ax02.text(0.35, 0.89,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELA20R[0]<50.0):
    line = "RELAY ON: Beam="+str(round(RELA20F[0],2))+"mA  SBCM="+str(round(RELA20F[1],1))+"mV\n"
    line = line+"Beam above TOSS Minimum=50mA:\nRELAY ON Beam > 50.0 ? FAIL"
    ax02.text(0.35, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY ON: Beam="+str(round(RELA20F[0],2))+"mA  SBCM="+str(round(RELA20F[1],1))+"mV\n"
    line = line+"Beam above TOSS Minimum=50mA:\nRELAY ON Beam > 50.0 ? PASS"
    ax02.text(0.35, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=good)

ax[1].plot(IW,'-o',color='blue')
ax[1].grid(True)
ax[1].set_xlabel("Time (AU)")
ax[1].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[1].tick_params(axis='y', labelcolor='blue')
ax12.plot(WBW,'-o',color='red')
ax12.plot(CBW,'-o',color='green')
ax12.plot(RBW,'-o',color='black')
ax12.set_ylabel("SBCM-B Status Bits",color='black')
ax[1].set_title("SBCM-B 20% Fill Functional Test")
ax12.set_yticks([0,1,2,3,4,5])
ax12.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT OFF: Beam="+str(round(WDTB20F[0],2))+"mA  SBCM="+str(round(WDTB20F[1],1))+"mV"
ax12.text(0.35, 0.96,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP OFF: Beam="+str(round(COMB20F[0],2))+"mA  SBCM="+str(round(COMB20F[1],1))+"mV"
ax12.text(0.35, 0.89,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELB20R[0]<50.0):
    line = "RELAY ON: Beam="+str(round(RELB20F[0],2))+"mA  SBCM="+str(round(RELB20F[1],1))+"mV\n"
    line = line+"Beam above TOSS Minimum=50mA:\nRELAY ON Beam > 50.0 ? FAIL"
    ax12.text(0.35, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY ON: Beam="+str(round(RELB20F[0],2))+"mA  SBCM="+str(round(RELB20F[1],1))+"mV\n"
    line = line+"Beam above TOSS Minimum=50mA:\nRELAY ON Beam > 50.0 ? PASS"
    ax12.text(0.35, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=good)

plt.tight_layout()
plt.pause(0.1)
plt.pause(0.1)
fa.savefig('SBCM_20pctFillBeamFallingFunctTest_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_20pctFillBeamFallingFunctTest_'+year+'.png',7*inch,9*inch)
elements.append(im)

# Create Table for Functional Test with 90% Fill Pattern and Beam Increasing:
tdata = []
rowH = []
tdata.append(['SBCM Functional Scan with 90% Fill and Increasing Beam','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['file:  '+ftestR90,'','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'
              ,'','Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'])
rowH.append(0.4*inch)

with open(ftestR90) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]
N = int(len(L))
WDTA90R=[0,0]
COMA90R=[0,0]
RELA90R=[0,0]
WDTB90R=[0,0]
COMB90R=[0,0]
RELB90R=[0,0]
AW=[]
BW=[]
IW=[]
WAW=[]
CAW=[]
RAW=[]
WBW=[]
CBW=[]
RBW=[]
target = 0.0
for i in range(0,N):
    Z = L[i].split(',')
    I=float(Z[0])
    A=float(Z[1])
    B=float(Z[2])
    WA=int(Z[3])
    CA=int(Z[4])
    RA=int(Z[5])
    WB=int(Z[6])
    CB=int(Z[7])
    RB=int(Z[8])
    if(I > target):
        target = target + 1
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTA90R[0]==0 and WA==1):
        WDTA90R[0] = I
        WDTA90R[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTB90R[0]==0 and WB==1):
        WDTB90R[0] = I
        WDTB90R[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMA90R[0]==0 and CA==2):
        COMA90R[0] = I
        COMA90R[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMB90R[0]==0 and CB==2):
        COMB90R[0] = I
        COMB90R[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELA90R[0]==0 and RA==3):
        RELA90R[0] = I
        RELA90R[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELB90R[0]==0 and RB==3):
        RELB90R[0] = I
        RELB90R[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)

N = int(len(AW)/2)           
for i in range(0,N):
    dat = [str(round(IW[i],2)),str(round(AW[i],2)),str(WAW[i])+','+str(CAW[i])+','+str(RAW[i]),
           str(round(BW[i],2)),str(WBW[i])+','+str(CBW[i])+','+str(RBW[i]),'',
           str(round(IW[N+i],2)),str(round(AW[N+i],2)),str(WAW[N+i])+','+str(CAW[N+i])+','+str(RAW[N+i]),
           str(round(BW[N+i],2)),str(WBW[N+i])+','+str(CBW[N+i])+','+str(RBW[N+i])]                                                                                    
    tdata.append(dat)
    rowH.append(0.22*inch)  
tdata.append(["Beam: Storage Ring Beam as Measured by the EPS PLC Chassis in mA"])
rowH.append(0.22*inch)
tdata.append(["Filt-A: Chain-A Rectifier Module Filter Output Measured by the Keithley 2100 in mV"])
rowH.append(0.22*inch)
tdata.append(["Bits-A: Chain-A State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC"])
rowH.append(0.22*inch)
tdata.append(["Filt-B: Chain-B Rectifier Module Filter Output Measured by the Keithley 2100 in mV"])
rowH.append(0.22*inch)
tdata.append(["Bits-B: Chain-B State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC"])
rowH.append(0.22*inch)
colW = [0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch,0.07*inch,0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch]
elements.append(PageBreak())     
t2=Table(tdata,colWidths=colW,rowHeights=rowH,style=[
                ('SPAN',(0,0),(10,0)),
                ('SPAN',(0,1),(10,1)),
                ('BACKGROUND',(0,0),(10,1),colors.lemonchiffon),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('LINEABOVE',(0,1),(10,1),2,colors.black),
                ('LINEABOVE',(0,2),(10,2),2,colors.black),
                ('LINEABOVE',(0,3),(10,3),2,colors.black),
                ('LINEABOVE',(0,36),(10,36),2,colors.black),
                ('BACKGROUND',(0,36),(10,40),colors.lemonchiffon),
                ('SPAN',(0,36),(10,36)),
                ('SPAN',(0,37),(10,37)),
                ('SPAN',(0,38),(10,38)),
                ('SPAN',(0,39),(10,39)),
                ('SPAN',(0,40),(10,40)),
                ])
elements.append(t2)

fa,ax = plt.subplots(2,1,figsize=(7,9))
ax02 = ax[0].twinx()
ax12 = ax[1].twinx()

ax[0].plot(IW,'-o',color='blue')
ax[0].grid(True)
ax[0].set_xlabel("Time (AU)")
ax[0].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[0].set_title("SBCM-A 90% Fill Functional Test")
ax[0].tick_params(axis='y', labelcolor='blue')
ax02.plot(WAW,'-o',color='red')
ax02.plot(CAW,'-o',color='green')
ax02.plot(RAW,'-o',color='black')
ax02.set_ylabel("SBCM-A Status Bits",color='black')
ax02.set_yticks([0,1,2,3,4,5])
ax02.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT ON: Beam="+str(round(WDTA90R[0],2))+"mA  SBCM="+str(round(WDTA90R[1],1))+"mV"
ax02.text(0.05, 0.96,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP ON: Beam="+str(round(COMA90R[0],2))+"mA  SBCM="+str(round(COMA90R[1],1))+"mV"
ax02.text(0.05, 0.89,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELA90R[0]<54.0):
    line = "RELAY ON: Beam="+str(round(RELA90R[0],2))+"mA  SBCM="+str(round(RELA90R[1],1))+"mV\n"
    line = line+"RELAY ON Beam above I(TOSS)=54mA:\nRELAY ON Beam > 54.0 ? FAIL"
    ax02.text(0.05, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY ON: Beam="+str(round(RELA90R[0],2))+"mA  SBCM="+str(round(RELA90R[1],1))+"mV\n"
    line = line+"RELAY ON Beam above I(TOSS)=54mA:\nRELAY ON Beam > 54.0 ? PASS"
    ax02.text(0.05, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=good)

ax[1].plot(IW,'-o',color='blue')
ax[1].grid(True)
ax[1].set_xlabel("Time (AU)")
ax[1].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[1].set_title("SBCM-A 90% Fill Functional Test")
ax[1].tick_params(axis='y', labelcolor='blue')
ax12.plot(WBW,'-o',color='red')
ax12.plot(CBW,'-o',color='green')
ax12.plot(RBW,'-o',color='black')
ax12.set_ylabel("SBCM-B Status Bits",color='black')
ax12.set_yticks([0,1,2,3,4,5])
ax12.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT ON: Beam="+str(round(WDTB90R[0],2))+"mA  SBCM="+str(round(WDTB90R[1],1))+"mV"
ax12.text(0.05, 0.96,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP ON: Beam="+str(round(COMB90R[0],2))+"mA  SBCM="+str(round(COMB90R[1],1))+"mV"
ax12.text(0.05, 0.89,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELB90R[0]<54.0):
    line = "RELAY ON: Beam="+str(round(RELB90R[0],2))+"mA  SBCM="+str(round(RELB90R[1],1))+"mV\n"
    line = line+"RELAY ON Beam above I(TOSS)=54mA:\nRELAY ON Beam > 54.0 ? FAIL"
    ax12.text(0.05, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY ON: Beam="+str(round(RELB90R[0],2))+"mA  SBCM="+str(round(RELB90R[1],1))+"mV\n"
    line = line+"RELAY ON Beam above I(TOSS)=54mA:\nRELAY ON Beam > 54.0 ? PASS"
    ax12.text(0.05, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=good)

plt.tight_layout()
plt.pause(0.1)
plt.pause(0.1)
fa.savefig('SBCM_90pctFillBeamRisingFunctTest_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_90pctFillBeamRisingFunctTest_'+year+'.png',7*inch,9*inch)
elements.append(im)
            
# Create Table for Functional Test with 90% Fill Pattern and Beam Decreasing:
tdata = []
rowH = []
tdata.append(['SBCM Functional Scan with 90% Fill and Decreasing Beam','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['file:  '+ftestF90,'','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'
              ,'','Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'])
rowH.append(0.4*inch)

with open(ftestF90) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]
N = int(len(L))
WDTA90F=[0,0]
COMA90F=[0,0]
RELA90F=[0,0]
WDTB90F=[0,0]
COMB90F=[0,0]
RELB90F=[0,0]
AW=[]
BW=[]
IW=[]
WAW=[]
CAW=[]
RAW=[]
WBW=[]
CBW=[]
RBW=[]
target = 70.0
for i in range(0,N):
    Z = L[i].split(',')
    I=float(Z[0])
    A=float(Z[1])
    B=float(Z[2])
    WA=int(Z[3])
    CA=int(Z[4])
    RA=int(Z[5])
    WB=int(Z[6])
    CB=int(Z[7])
    RB=int(Z[8])
    if(I < target):
        if((target-1)<I):
            target = target - 1
        else:
            target = I - 1
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTA90F[0]==0 and WA==0):
        WDTA90F[0] = I
        WDTA90F[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTB90F[0]==0 and WB==0):
        WDTB90F[0] = I
        WDTB90F[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMA90F[0]==0 and CA==0):
        COMA90F[0] = I
        COMA90F[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMB90F[0]==0 and CB==0):
        COMB90F[0] = I
        COMB90F[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELA90F[0]==0 and RA==0):
        RELA90F[0] = I
        RELA90F[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELB90F[0]==0 and RB==0):
        RELB90F[0] = I
        RELB90F[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)

N = int(len(AW)/2)           
for i in range(0,N):
    dat = [str(round(IW[i],2)),str(round(AW[i],2)),str(WAW[i])+','+str(CAW[i])+','+str(RAW[i]),
           str(round(BW[i],2)),str(WBW[i])+','+str(CBW[i])+','+str(RBW[i]),'',
           str(round(IW[N+i],2)),str(round(AW[N+i],2)),str(WAW[N+i])+','+str(CAW[N+i])+','+str(RAW[N+i]),
           str(round(BW[N+i],2)),str(WBW[N+i])+','+str(CBW[N+i])+','+str(RBW[N+i])]                                                                                    
    tdata.append(dat)
    rowH.append(0.22*inch)  
tdata.append(["Beam: Storage Ring Beam as Measured by the EPS PLC Chassis in mA"])
rowH.append(0.22*inch)
tdata.append(["Filt-A: Chain-A Rectifier Module Filter Output Measured by the Keithley 2100 in mV"])
rowH.append(0.22*inch)
tdata.append(["Bits-A: Chain-A State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC"])
rowH.append(0.22*inch)
tdata.append(["Filt-B: Chain-B Rectifier Module Filter Output Measured by the Keithley 2100 in mV"])
rowH.append(0.22*inch)
tdata.append(["Bits-B: Chain-B State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC"])
rowH.append(0.22*inch)
colW = [0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch,0.07*inch,0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch]
elements.append(PageBreak())     
t2=Table(tdata,colWidths=colW,rowHeights=rowH,style=[
                ('SPAN',(0,0),(10,0)),
                ('SPAN',(0,1),(10,1)),
                ('BACKGROUND',(0,0),(10,1),colors.lemonchiffon),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('LINEABOVE',(0,1),(10,1),2,colors.black),
                ('LINEABOVE',(0,2),(10,2),2,colors.black),
                ('LINEABOVE',(0,3),(10,3),2,colors.black),
                ('LINEABOVE',(0,36),(10,36),2,colors.black),
                ('BACKGROUND',(0,36),(10,40),colors.lemonchiffon),
                ('SPAN',(0,36),(10,36)),
                ('SPAN',(0,37),(10,37)),
                ('SPAN',(0,38),(10,38)),
                ('SPAN',(0,39),(10,39)),
                ('SPAN',(0,40),(10,40)),
                ])
elements.append(t2)

fa,ax = plt.subplots(2,1,figsize=(7,9))
ax02 = ax[0].twinx()
ax12 = ax[1].twinx()

ax[0].plot(IW,'-o',color='blue')
ax[0].grid(True)
ax[0].set_xlabel("Time (AU)")
ax[0].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[0].set_title("SBCM-A 90% Fill Functional Test")
ax[0].tick_params(axis='y', labelcolor='blue')
ax02.plot(WAW,'-o',color='red')
ax02.plot(CAW,'-o',color='green')
ax02.plot(RAW,'-o',color='black')
ax02.set_ylabel("SBCM-A Status Bits",color='black')
ax02.set_yticks([0,1,2,3,4,5])
ax02.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT OFF: Beam="+str(round(WDTA90F[0],2))+"mA  SBCM="+str(round(WDTA90F[1],1))+"mV"
ax02.text(0.35, 0.96,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP OFF: Beam="+str(round(COMA90F[0],2))+"mA  SBCM="+str(round(COMA90F[1],1))+"mV"
ax02.text(0.35, 0.89,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELA90F[0]<54.0):
    line = "RELAY ON: Beam="+str(round(RELA90F[0],2))+"mA  SBCM="+str(round(RELA90F[1],1))+"mV\n"
    line = line+"RELAY ON Beam above I(TOSS)=54mA:\nRELAY ON Beam > 54.0 ? FAIL"
    ax02.text(0.35, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY ON: Beam="+str(round(RELA90F[0],2))+"mA  SBCM="+str(round(RELA90F[1],1))+"mV\n"
    line = line+"RELAY ON Beam above I(TOSS)=54mA:\nRELAY ON Beam > 54.0 ? PASS"
    ax02.text(0.35, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=good)

ax[1].plot(IW,'-o',color='blue')
ax[1].grid(True)
ax[1].set_xlabel("Time (AU)")
ax[1].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[1].tick_params(axis='y', labelcolor='blue')
ax12.plot(WBW,'-o',color='red')
ax12.plot(CBW,'-o',color='green')
ax12.plot(RBW,'-o',color='black')
ax12.set_ylabel("SBCM-B Status Bits",color='black')
ax[1].set_title("SBCM-B 90% Fill Functional Test")
ax12.set_yticks([0,1,2,3,4,5])
ax12.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT OFF: Beam="+str(round(WDTB90F[0],2))+"mA  SBCM="+str(round(WDTB90F[1],1))+"mV"
ax12.text(0.35, 0.96,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP OFF: Beam="+str(round(COMB90F[0],2))+"mA  SBCM="+str(round(COMB90F[1],1))+"mV"
ax12.text(0.35, 0.89,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELB90F[0]<54.0):
    line = "RELAY ON: Beam="+str(round(RELB90F[0],2))+"mA  SBCM="+str(round(RELB90F[1],1))+"mV\n"
    line = line+"RELAY ON Beam above I(TOSS)=54mA:\nRELAY ON Beam > 54.0 ? FAIL"
    ax12.text(0.35, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY ON: Beam="+str(round(RELB90F[0],2))+"mA  SBCM="+str(round(RELB90F[1],1))+"mV\n"
    line = line+"RELAY ON Beam above I(TOSS)=54mA:\nRELAY ON Beam > 54.0 ? PASS"
    ax12.text(0.35, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=good)

plt.tight_layout()
plt.pause(0.1)
plt.pause(0.1)
fa.savefig('SBCM_90pctFillBeamFallingFunctTest_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_90pctFillBeamFallingFunctTest_'+year+'.png',7*inch,8.5*inch)
elements.append(im)

tdata = []
tdata.append(["All Tests for this Procedure have PASSED"])
tdata.append(["TOSS SBCM Calibration Final Result:  PASS"])

ta=Table(tdata,6*inch,[0.32*inch,0.32*inch],style=[
                ('BACKGROUND',(0,0),(0,1),colors.palegreen),
                ('FONTSIZE',(0,0),(0,1),14),
                ('VALIGN',(0,0),(0,1),'MIDDLE'),
                ('GRID',(0,0),(-1,-1),1,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ])

elements.append(ta)
       
###############################################################################################
# End of Report...Building....
###############################################################################################
doc.build(elements)
