import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
from reportlab.lib.pagesizes import letter, inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Image, PageBreak, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
import os
from time import sleep

props = dict(boxstyle='round', facecolor='wheat', alpha=0.5)
good = dict(boxstyle='round', facecolor='palegreen', alpha=0.5)
bad = dict(boxstyle='round', facecolor='lightcoral', alpha=0.5)

###############################################################################################
# Setup Parameters for SBCM Calibration for TOSS (Adjust these Parameters as Needed)
###############################################################################################
year = '2026'

Title = 'Results for SBCM Calibration for TOSS: NSLSII-INS-PRC-005'
CalDate = '1/17/2026'
ReportDate = '1/21/2026'
Engineer = 'Kato Bouthsarath'
Technician = 'Anthony Caracappa'

ScopeMAN = 'Tektronix'
ScopeMOD = 'MSO64B'
ScopeSN =  'B013046'
ScopeCAL = '12/29/2026'

SourceMAN = 'Rohde & Schwarz'
SourceMOD = 'SMB100B'
SourceSN =  '102463'
SourceCAL = '5/8/2026'

DMM1MAN = 'Keithley'
DMM1MOD = '2100'
DMM1SN = '8020356'
DMM1CAL = '12/29/2026'

DMM2MAN = 'Keithley'
DMM2MOD = '2100'
DMM2SN = '8020357'
DMM2CAL = '12/29/2026'

###############################################################################################
# Manual Measurements
###############################################################################################

# Rectifier Offset Adjutment (mV):
RectOffsetAold = 5.9
RectOffsetAnew = 5.263
RectOffsetBold = 34.1
RectOffsetBnew = 34.365

# Downconverted Frequency Adjustment (MHz):
freqAold = 1.80
freqAnew = 1.773
freqBold = 1.81
freqBnew = 1.804

#Downconverted Output Level for Test RF = 499.68MHz @ -10.0dBm:
TestLevelA = 266.2
TestLevelB = 247.8

# Voltage Supply Measurements:
vn_12 = -12.025
vp_12 = 12.004
vn_5 = -5.081
vp_5 = 5.118

# start index and target length for functional test data
start = 0
end_cut = 50 # number of points to cut from data for functional test



###############################################################################################
# Data Files for SBCM DCCT Calibration for TOSS (Adjust these Parameters as Needed)
###############################################################################################

bscan =    'BandwidthScan.py'             #Python Script to measure the Bandwidth of the SBCM Rectifier Modules
fcurve =   'CharacteristicCurve.py'       #Python Script to measure the Characteristic Curve for each Chain
fscan =    'BeamScan.py'                  #Python Script to measure the Response with Beam from 0 to about 200mA
ftest =    'FunctionalTest.py'            #Python Script to measure when the WDT, COMP, and RELAY Bits turn ON or OFF
frep  =    'ProcessSBCM.py'               #This Python Script generating the Report PDF
fccA =     f'SBCM-A_{year}_CharCurve.txt'    #File Generated during the Characteristic Curve measurement for Chain A
fccB =     f'SBCM-B_{year}_CharCurve.txt'    #File Generated during the Characteristic Curve measurement for Chain B
fbm90 =    f'SBCM_BeamScanFull_90pctFill_{year}.txt'    #File Generated during the Beam Scan for 90% Fill Pattern
fbm20 =    f'SBCM_BeamScanFull_20pctFill_{year}.txt'    #File Generated during the Beam Scan for 20% Fill Pattern
ftestR90 = f'SBCM_FunctionalTestRising_90pctFill_{year}.txt'  #File Generated during Functional Test, 90% Fill, Beam Increasing
ftestF90 = f'SBCM_FunctionalTestFalling_90pctFill_{year}.txt' #File Generated during Functional Test, 90% Fill, Beam Decreasing
ftestR20 = f'SBCM_FunctionalTestRising_20pctFill_{year}.txt'  #File Generated during Functional Test, 20% Fill, Beam Increasing
ftestF20 = f'SBCM_FunctionalTestFalling_20pctFill_{year}.txt' #File Generated during Functional Test, 20% Fill, Beam Decreasing
bscanA =   f'SBCM-A_{year}_BWScan.txt'    #File Generated during the Bandwidth Scan for Chain A
bscanB =   f'SBCM-B_{year}_BWScan.txt'    #File Generated during the Bandwidth Scan for Chain B
rdelayA =   f'SBCM-A_{year}_RelayDelay.txt'    #File Generated during the Relay Delay Measurement for Chain A
rdelayB =   f'SBCM-B_{year}_RelayDelay.txt'    #File Generated during the Relay Delay Measurement for Chain B

freport = f'SBCM_Calibration_{year}.pdf'   #File Generated by this script for the Calibration Report
if os.path.exists(freport):
    x = input("\n\nFile Exists! Make sure this file is not in use then\nEnter '1' to overwrite or '0' to abort: ")
    if int(x)==1:
        try:
            os.rename(freport,freport)
            print("Available!")
        except OSError as e:
            print("****** ERROR ******\n\n"+freport+" is in use. Please close the file and try again.")
            exit()
    else:
        exit()

###############################################################################################
# Start of Report:
###############################################################################################

doc = SimpleDocTemplate(freport, pagesize=letter, rightMargin=30,leftMargin=30, topMargin=30,bottomMargin=18)
elements = []

tdata = []
tdata.append([Title])
tdata.append(["Procedure Performed on "+CalDate+" by "+Engineer+" and "+Technician])
tdata.append(["Analysis Performed on "+ReportDate+" by "+Engineer])

ta=Table(tdata,6*inch,[0.4*inch,0.22*inch,0.22*inch],style=[
                ('BACKGROUND',(0,0),(0,0),colors.lemonchiffon),
                ('VALIGN',(0,0),(0,0),'MIDDLE'),
                ('LINEABOVE',(0,1),(0,1),2,colors.black),
                ('FONTSIZE', (0,0), (0,0), 12),
                ('GRID',(0,0),(-1,-1),1,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ])

elements.append(ta)

tdata = []
tdata.append(["Test Equipment Used for Calibration","",""])
tdata.append(["Oscilloscope","Manufacturer",ScopeMAN])
tdata.append(["","Model Number",ScopeMOD])
tdata.append(["","Serial Number",ScopeSN])
tdata.append(["","Calibration Expiration",ScopeCAL])
tdata.append(["RF Source","Manufacturer",SourceMAN])
tdata.append(["","Model Number",SourceMOD])
tdata.append(["","Serial Number",SourceSN])
tdata.append(["","Calibration Expiration",SourceCAL])
tdata.append(["DMM1","Manufacturer",DMM1MAN])
tdata.append(["","Model Number",DMM1MOD])
tdata.append(["","Serial Number",DMM1SN])
tdata.append(["","Calibration Expiration",DMM1CAL])
tdata.append(["DMM2","Manufacturer",DMM2MAN])
tdata.append(["","Model Number",DMM2MOD])
tdata.append(["","Serial Number",DMM2SN])
tdata.append(["","Calibration Expiration",DMM2CAL])
tdata.append(["Python Scripts","Bandwidth Scan",bscan])
tdata.append(["","Characteristic Curve",fcurve])
tdata.append(["","Beam Scan",fscan])
tdata.append(["","Report Generation",ftest])
tdata.append(["Output File","DCCT Report",frep])

elements.append(Spacer(width=1,height=0.1*inch))
t0=Table(tdata,2*inch,0.22*inch,style=[
                ('SPAN',(0,0),(2,0)),
                ('BACKGROUND',(0,0),(2,0),colors.lemonchiffon),
                ('LINEABOVE',(0,1),(2,1),2,colors.black),
                ('SPAN',(0,1),(0,4)),
                ('LINEABOVE',(0,5),(2,5),2,colors.black),
                ('SPAN',(0,5),(0,8)),
                ('LINEABOVE',(0,9),(2,9),2,colors.black),
                ('SPAN',(0,9),(0,12)),
                ('LINEABOVE',(0,13),(2,13),2,colors.black),
                ('SPAN',(0,13),(0,16)),
                ('LINEABOVE',(0,17),(2,17),2,colors.black),
                ('SPAN',(0,17),(0,21)),
                ('GRID',(0,0),(-1,-1),1,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('VALIGN',(0,1),(0,21),'MIDDLE'),
                ('BACKGROUND',(0,1),(1,21),colors.lemonchiffon),
                ])

elements.append(t0)

# Create Table for Voltage Supply Measurements:

tdata = []
tdata.append(["Voltage Supply Measurements","",""])
tdata.append(["Actual Voltage (V)","Measured Voltage (V)","Status"])
tdata.append(["-12.0 V",str(vn_12),"PASS"])
tdata.append(["+12.0 V","+" + str(vp_12),"PASS"])
tdata.append(["-5.0 V",str(vn_5),"PASS"])
tdata.append(["+5.0 V","+" + str(vp_5),"PASS"])
elements.append(Spacer(width=1,height=0.1*inch))

ta=Table(tdata,2*inch,0.22*inch,style=[
                ('SPAN',(0,0),(2,0)),
                ('BACKGROUND',(0,0),(2,1),colors.lemonchiffon),
                ('LINEABOVE',(0,1),(2,1),2,colors.black),
                ('LINEABOVE',(0,2),(2,2),2,colors.black),
                ('GRID',(0,0),(-1,-1),1,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('VALIGN',(0,2),(0,5),'MIDDLE'),
                ('BACKGROUND',(0,2),(0,5),colors.lightblue),
                ('BACKGROUND',(2,2),(2,5),colors.palegreen),
                ])

elements.append(ta)

# Create Table for Preliminary Settings Adjustments:

rowH=[]
tdata = []
tdata.append(["Preliminary Settings Adjustments",'',''])
rowH.append(0.4*inch)
tdata.append(["Adjustments made on "+CalDate+" by the CE: "+Engineer,'',''])
rowH.append(0.22*inch)
tdata.append(["Adjustment","Set To:","Status"])
rowH.append(0.22*inch)
tdata.append(["Rectifier Offset A",str(RectOffsetAnew)+'mV',"PASS"])
rowH.append(0.22*inch)
tdata.append(["Rectifier Offset B",str(RectOffsetBnew)+'mV',"PASS"])
rowH.append(0.22*inch)
tdata.append(["Downconverted Frequency A",str(freqAnew)+"MHz","PASS"])
rowH.append(0.22*inch)
tdata.append(["Downconverted Frequency B",str(freqBnew)+"MHz","PASS"])
rowH.append(0.22*inch)
tdata.append(["Measurement","Reading","Status"])
rowH.append(0.22*inch)
tdata.append(["Downconverted Frequency A Level",str(TestLevelA)+"mVpp","PASS"])
rowH.append(0.22*inch)
tdata.append(["Downconverted Frequency B Level",str(TestLevelB)+"mVpp","PASS"])
rowH.append(0.22*inch)

colW = [3*inch,1*inch,1*inch]
elements.append(Spacer(width=1,height=0.1*inch))
ta=Table(tdata,colWidths=colW,rowHeights=rowH,style=[
                ('SPAN',(0,0),(2,0)),
                ('SPAN',(0,1),(2,1)),
                ('BACKGROUND',(0,0),(2,2),colors.lemonchiffon),
                ('BACKGROUND',(0,3),(0,6),colors.lightblue),
                ('BACKGROUND',(0,7),(0,9),colors.lightblue),
                ('BACKGROUND',(2,3),(2,6),colors.palegreen),
                ('BACKGROUND',(2,7),(2,9),colors.palegreen),
                ('VALIGN',(0,0),(0,0),'MIDDLE'),
                ('LINEABOVE',(0,1),(2,1),2,colors.black),
                ('LINEABOVE',(0,2),(2,2),2,colors.black),
                ('LINEABOVE',(0,3),(2,3),2,colors.black),
                ('LINEABOVE',(0,8),(2,8),2,colors.black),
                ('LINEABOVE',(0,7),(2,7),2,colors.black),
                ('BACKGROUND',(0,7),(2,7),colors.lemonchiffon),
                ('FONTSIZE', (0,0), (0,0), 12),
                ('GRID',(0,0),(-1,-1),1,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ])

elements.append(ta)

# Chain-A Relay Delay Measurement:

length = 950000 #Number of points in the measurement
data = np.loadtxt(rdelayA, delimiter=',')

# Take last `length` rows
data = data[-length:, :]

time = data[:, 0]
R    = data[:, 1]
RF   = data[:, 2]

# Envelope extraction
rf_abs = np.abs(RF)

# Moving average window (adjust if needed)
win = 2000
rf_env = np.convolve(rf_abs, np.ones(win)/win, mode='same')

rf_threshold = 0.1 * np.max(rf_env)

rf_on = rf_env > rf_threshold

# Require RF to stay OFF for N consecutive samples
N_hold = 5000

rf_off_idx = None
for i in range(len(rf_on) - N_hold):
    if rf_on[i] and not np.any(rf_on[i+1:i+1+N_hold]):
        rf_off_idx = i + 1
        break
dt = np.mean(np.diff(time))   # seconds per sample
rf_fall_time = time[rf_off_idx]


relay_threshold = 1.0

relay_on = R > relay_threshold
relay_fall_idx = np.where((relay_on[:-1]) & (~relay_on[1:]))[0][0] + 1

relay_fall_time = time[relay_fall_idx]
relay_delayA = relay_fall_time - rf_fall_time    

plt.figure(figsize=(11,7))
plt.plot(time*1e3, RF, label='RF Input: 8 dBm @\n499.68 MHz')
plt.plot(time*1e3, R, label='Relay')
plt.legend(loc='upper right')

plt.axvline(rf_fall_time*1e3, linestyle='--')
plt.axvline(relay_fall_time*1e3, linestyle='--')

# Midpoint time (ms)
t_mid_ms = 0.5 * (rf_fall_time + relay_fall_time) * 1e3
y_arrow = 20
y_text  = 18

# Draw double-headed arrow
plt.annotate(
    '',
    xy=(relay_fall_time*1e3, y_arrow),
    xytext=(rf_fall_time*1e3, y_arrow),
    arrowprops=dict(arrowstyle='<->', linewidth=1.5, color='black')
)

# Add delay label
plt.text(
    t_mid_ms,
    y_text,
    f"Delay = {relay_delayA*1e3:.3f} ms",
    ha='center',
    va='bottom',
    fontsize=10,
    bbox=dict(boxstyle='round,pad=0.25', facecolor='white', edgecolor='black')
)
if((relay_delayA*1e3) <70.0):
    plt.text(0.05, 0.68, "Delay < 70.0 ms?: PASS",fontsize=12,transform=plt.gca().transAxes, verticalalignment='top', bbox=good)
else:
    plt.text(0.05, 0.68, "Delay < 70.0 ms?: FAIL",fontsize=12,transform=plt.gca().transAxes, verticalalignment='top', bbox=bad)

plt.legend()
plt.xlabel('Time (ms)')
plt.ylabel('Voltage (V)')
plt.title('SBCM Chain-A Relay Delay Measurement')
plt.grid(True)
plt.legend(loc='upper right')
plt.pause(0.5)

fname = f"SBCM-A_{year}_RelayDelay.png"
plt.savefig(fname)  
sleep(1)
plt.close(plt.gcf())

# Chain-B Relay Delay Measurement:

length = 950000 #Number of points in the measurement
data = np.loadtxt(rdelayB, delimiter=',')

# Take last `length` rows
data = data[-length:, :]

time = data[:, 0]
R    = data[:, 1]
RF   = data[:, 2]

# Envelope extraction
rf_abs = np.abs(RF)

# Moving average window (adjust if needed)
win = 2000
rf_env = np.convolve(rf_abs, np.ones(win)/win, mode='same')

rf_threshold = 0.1 * np.max(rf_env)

rf_on = rf_env > rf_threshold

# Require RF to stay OFF for N consecutive samples
N_hold = 5000

rf_off_idx = None
for i in range(len(rf_on) - N_hold):
    if rf_on[i] and not np.any(rf_on[i+1:i+1+N_hold]):
        rf_off_idx = i + 1
        break
dt = np.mean(np.diff(time))   # seconds per sample
rf_fall_time = time[rf_off_idx]


relay_threshold = 1.0

relay_on = R > relay_threshold
relay_fall_idx = np.where((relay_on[:-1]) & (~relay_on[1:]))[0][0] + 1

relay_fall_time = time[relay_fall_idx]
relay_delayB = relay_fall_time - rf_fall_time        

plt.figure(figsize=(11,7))
plt.plot(time*1e3, RF, label='RF Input: 8 dBm @\n499.68 MHz')
plt.plot(time*1e3, R, label='Relay')
plt.legend(loc='upper right')

plt.axvline(rf_fall_time*1e3, linestyle='--')
plt.axvline(relay_fall_time*1e3, linestyle='--')

# Midpoint time (ms)
t_mid_ms = 0.5 * (rf_fall_time + relay_fall_time) * 1e3
y_arrow = 20
y_text  = 18

# Draw double-headed arrow
plt.annotate(
    '',
    xy=(relay_fall_time*1e3, y_arrow),
    xytext=(rf_fall_time*1e3, y_arrow),
    arrowprops=dict(arrowstyle='<->', linewidth=1.5, color='black')
)

# Add delay label
plt.text(
    t_mid_ms,
    y_text,
    f"Delay = {relay_delayB*1e3:.3f} ms",
    ha='center',
    va='bottom',
    fontsize=10,
    bbox=dict(boxstyle='round,pad=0.25', facecolor='white', edgecolor='black')
)
if((relay_delayB*1e3) <70.0):
    plt.text(0.05, 0.68, "Delay < 70.0 ms?: PASS",fontsize=12,transform=plt.gca().transAxes, verticalalignment='top', bbox=good)
else:
    plt.text(0.05, 0.68, "Delay < 70.0 ms?: FAIL",fontsize=12,transform=plt.gca().transAxes, verticalalignment='top', bbox=bad)

plt.legend()
plt.xlabel('Time (ms)')
plt.ylabel('Voltage (V)')
plt.title('SBCM Chain-B Relay Delay Measurement')
plt.grid(True)
plt.legend(loc='upper right')
plt.pause(0.5)

fname = f"SBCM-B_{year}_RelayDelay.png"
plt.savefig(fname)
sleep(1)
plt.close(plt.gcf())


# Table for Relay Delay Measurements:
tdata = []
rowH = []
tdata.append(["SBCM Relay Delay Measurements",'',''])
rowH.append(0.4*inch)
tdata.append(["The relay delay is measured as the time difference between the falling edge\n"
            + "of the RF input signal and the falling edge of the relay output signal.","",""])
rowH.append(0.4*inch)
tdata.append(["","Measured Delay (ms)","Status"])
rowH.append(0.22*inch)
tdata.append(["Chain A Relay Delay",str(round(relay_delayA*1e3,3))
,"PASS" if (relay_delayA*1e3)<70.0 else "FAIL"])
rowH.append(0.22*inch)
tdata.append(["Chain B Relay Delay",str(round(relay_delayB*1e3,3))
,"PASS" if (relay_delayB*1e3)<70.0 else "FAIL"])
rowH.append(0.22*inch)
elements.append(Spacer(width=1,height=0.3*inch))
colW = [2*inch,2*inch,1*inch]

ta=Table(tdata,colWidths=colW,rowHeights=rowH,style=[
                ('SPAN',(0,0),(2,0)),
                ('SPAN',(0,1),(2,1)),
                ('BACKGROUND',(0,0),(2,2),colors.lemonchiffon),
                ('LINEABOVE',(0,1),(2,1),2,colors.black),
                ('LINEABOVE',(0,2),(2,2),2,colors.black),
                ('GRID',(0,0),(-1,-1),1,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('VALIGN',(0,3),(0,4),'MIDDLE'),
                ('BACKGROUND',(0,3),(0,4),colors.lightblue),
                ('BACKGROUND',(2,3),(2,4),colors.palegreen) if (relay_delayA*1e3)<70.0 and (relay_delayB*1e3)<70.0 else
                ('BACKGROUND',(2,3),(2,4),colors.lightcoral),
                ('VALIGN',(0,0),(0,0),'MIDDLE'),
                ('FONTSIZE', (0,0), (0,0), 12),
                ])
elements.append(ta)

# Insert Relay Delay Images into Report:
imA = Image('SBCM-A_'+year+'_RelayDelay.png',8*inch,4.35*inch)
elements.append(imA)

imB = Image('SBCM-B_'+year+'_RelayDelay.png',8*inch,4.35*inch)
elements.append(imB)

# Create Table for Chain-A Bandwidth Measurement:

tdata = []
rowH = []
tdata.append(["SBCM Chain-A Bandwidth Measurement",'','','','file:  '+bscanA,'','','',''])
rowH.append(0.22*inch)
tdata.append(["Freq\n(Hz)","Vpp\n(V)","Amp\n(dB)","Freq\n(Hz)","Vpp\n(V)","Amp\n(dB)","Freq\n(Hz)","Vpp\n(V)","Amp\n(dB)"])
rowH.append(0.4*inch)
colW = [0.6*inch,0.8*inch,0.8*inch,0.6*inch,0.8*inch,0.8*inch,0.6*inch,0.8*inch,0.8*inch]

with open(bscanA) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]
Hz=np.zeros(75)
Vpkpk=np.zeros(75)
for i in range(0,25):
    Z = L[i].split(',')
    Hz[i] = float(Z[0])
    Vpkpk[i] = float(Z[1])
    W = L[i+25].split(',')
    Hz[i+25] = float(W[0])
    Vpkpk[i+25] = float(W[1])
    Y = L[i+50].split(',')
    Hz[i+50] = float(Y[0])
    Vpkpk[i+50] = float(Y[1])
    # Convert Vpkpk to dB relative to the first measured point (reference = 0 dB)
    # Use 20*log10 for voltage ratio. Protect against zero reference.
    ref = Vpkpk[0] if Vpkpk[0] != 0 else 1e-12
    Vdb_i = 20.0 * np.log10(Vpkpk[i] / ref)
    Vdb_i25 = 20.0 * np.log10(Vpkpk[i+25] / ref)
    Vdb_i50 = 20.0 * np.log10(Vpkpk[i+50] / ref)
    tdata.append([int(Hz[i]), round(Vpkpk[i], 4), round(Vdb_i, 2), int(Hz[i+25]), round(Vpkpk[i+25], 4), round(Vdb_i25, 2), int(Hz[i+50]), round(Vpkpk[i+50], 4), round(Vdb_i50, 2)])
    rowH.append(0.22*inch)
tdata.append(['The RF input is set to 499.68 MHz @ 0 dBm.','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Freq:    Amplitude Modulation Hz between 1 Hz and 300 Hz.','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Vpp: Measured voltage (pk-pk) of the demodulated signal coming from the Recitifier Module.','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Amp:    Measured amplitude (dB) of the demodulated signal coming from the Recitifer Module.\n 0 dB is referring to the first point of the data.','','','','','','','',''])
rowH.append(0.45*inch)

elements.append(PageBreak()) 

t2=Table(tdata,colWidths=colW,rowHeights=rowH,style=[
                ('SPAN',(0,0),(3,0)),
                ('SPAN',(4,0),(8,0)),
                ('BACKGROUND',(0,0),(8,0),colors.lemonchiffon),
                ('BACKGROUND',(0,1),(0,26),colors.lightblue),
                ('BACKGROUND',(3,1),(3,26),colors.lightblue),
                ('BACKGROUND',(6,1),(6,26),colors.lightblue),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('LINEABOVE',(0,1),(8,1),2,colors.black),
                ('LINEABOVE',(0,2),(8,2),1.5,colors.black),
                ('LINEBEFORE',(1,1),(1,26),1.5,colors.black),
                ('LINEBEFORE',(3,1),(3,26),2,colors.black),
                ('LINEBEFORE',(4,0),(4,26),1.5,colors.black),
                ('LINEBEFORE',(6,1),(6,26),2,colors.black),
                ('LINEBEFORE',(7,1),(7,26),1.5,colors.black),
                ('SPAN',(0,27),(8,27)),
                ('SPAN',(0,28),(8,28)),
                ('SPAN',(0,29),(8,29)),
                ('SPAN',(0,30),(8,30)),
                ('LINEABOVE',(0,27),(8,27),1.5,colors.black),
                ('BACKGROUND',(0,27),(8,30),colors.lemonchiffon),
                ])

elements.append(t2)

fname = f"SBCM_BandwidthA_{year}.png"

bscanA_fig = plt.figure(figsize=(6,4))
dbVpkpk = 20.0 * np.log10(Vpkpk / Vpkpk[0])

# Target amplitude
target_db = -3.0

# Find index where curve crosses -3 dB
idx = np.where(dbVpkpk <= target_db)[0][0]

# Take the point just above and just below -3 dB
x1, x2 = Hz[idx-1], Hz[idx]
y1, y2 = dbVpkpk[idx-1], dbVpkpk[idx]

# Linear fit: y = m*x + b
m, b = np.polyfit([x1, x2], [y1, y2], 1)

# Solve for frequency at -3 dB
hz_3db = (target_db - b) / m

plt.plot(Hz, dbVpkpk, '-o', markersize=5, linewidth=2)

# Mark -3 dB point
plt.axvline(
    hz_3db,
    linestyle='--',
    linewidth=1.5,
    color='red',
    label=f'-3 dB @ {hz_3db:.1f} Hz'
)

plt.legend()

plt.title('SBCM Chain-A Bandwidth Measurement')
plt.xlabel("Frequency (Hz)")
plt.ylabel("Amplitude (dB)")
plt.grid(True)
plt.pause(0.1)
bscanA_fig.savefig(fname, dpi=300, bbox_inches='tight')
sleep(1)
plt.close(bscanA_fig)


im = Image('SBCM_BandwidthA_'+year+'.png',4.7*inch,2.7*inch)
elements.append(Spacer(width=1,height=0.02*inch))
elements.append(im)

# Create Table for Chain-B Bandwidth Measurement:

tdata = []
rowH = []
tdata.append(["SBCM Chain-B Bandwidth Measurement",'','','','file:  '+bscanB,'','','',''])
rowH.append(0.22*inch)
tdata.append(["Freq\n(Hz)","Vpkpk\n(V)","Amp\n(dB)","Freq\n(Hz)","Vpkpk\n(V)","Amp\n(dB)","Freq\n(Hz)","Vpkpk\n(V)","Amp\n(dB)"])
rowH.append(0.4*inch)
colW = [0.6*inch,0.8*inch,0.8*inch,0.6*inch,0.8*inch,0.8*inch,0.6*inch,0.8*inch,0.8*inch]

with open(bscanB) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]
Hz=np.zeros(75)
Vpkpk=np.zeros(75)
for i in range(0,25):
    Z = L[i].split(',')
    Hz[i] = float(Z[0])
    Vpkpk[i] = float(Z[1])
    W = L[i+25].split(',')
    Hz[i+25] = float(W[0])
    Vpkpk[i+25] = float(W[1])
    Y = L[i+50].split(',')
    Hz[i+50] = float(Y[0])
    Vpkpk[i+50] = float(Y[1])
    # Convert Vpkpk to dB relative to the first measured point (reference = 0 dB)
    # Use 20*log10 for voltage ratio. Protect against zero reference.
    ref = Vpkpk[0] if Vpkpk[0] != 0 else 1e-12
    Vdb_i = 20.0 * np.log10(Vpkpk[i] / ref)
    Vdb_i25 = 20.0 * np.log10(Vpkpk[i+25] / ref)
    Vdb_i50 = 20.0 * np.log10(Vpkpk[i+50] / ref)
    tdata.append([int(Hz[i]), round(Vpkpk[i], 4), round(Vdb_i, 2), int(Hz[i+25]), round(Vpkpk[i+25], 4), round(Vdb_i25, 2), int(Hz[i+50]), round(Vpkpk[i+50], 4), round(Vdb_i50, 2)])
    rowH.append(0.22*inch)
tdata.append(['The RF input is set to 499.68 MHz @ 0 dBm.','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Freq:    Amplitude Modulation Hz between 1 Hz and 300 Hz.','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Vpkpk: Measured voltage (pk-pk) of the demodulated signal coming from the Recitifier Module.','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Amp:    Measured amplitude (dB) of the demodulated signal coming from the Recitifer Module.\n 0 dB is referring to the first point of the data.','','','','','','','',''])
rowH.append(0.45*inch)

elements.append(PageBreak()) 

t2=Table(tdata,colWidths=colW,rowHeights=rowH,style=[
                ('SPAN',(0,0),(3,0)),
                ('SPAN',(4,0),(8,0)),
                ('BACKGROUND',(0,0),(8,0),colors.lemonchiffon),
                ('BACKGROUND',(0,1),(0,26),colors.lightblue),
                ('BACKGROUND',(3,1),(3,26),colors.lightblue),
                ('BACKGROUND',(6,1),(6,26),colors.lightblue),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('LINEABOVE',(0,1),(8,1),2,colors.black),
                ('LINEABOVE',(0,2),(8,2),1.5,colors.black),
                ('LINEBEFORE',(1,1),(1,26),1.5,colors.black),
                ('LINEBEFORE',(3,1),(3,26),2,colors.black),
                ('LINEBEFORE',(4,0),(4,26),1.5,colors.black),
                ('LINEBEFORE',(6,1),(6,26),2,colors.black),
                ('LINEBEFORE',(7,1),(7,26),1.5,colors.black),
                ('SPAN',(0,27),(8,27)),
                ('SPAN',(0,28),(8,28)),
                ('SPAN',(0,29),(8,29)),
                ('SPAN',(0,30),(8,30)),
                ('LINEABOVE',(0,27),(8,27),1.5,colors.black),
                ('BACKGROUND',(0,27),(8,30),colors.lemonchiffon),
                ])

elements.append(t2)

fname = f"SBCM_BandwidthB_{year}.png"

bscanB_fig = plt.figure(figsize=(6,4))
dbVpkpk = 20.0 * np.log10(Vpkpk / Vpkpk[0])

# Target amplitude
target_db = -3.0

# Find index where curve crosses -3 dB
idx = np.where(dbVpkpk <= target_db)[0][0]

# Take the point just above and just below -3 dB
x1, x2 = Hz[idx-1], Hz[idx]
y1, y2 = dbVpkpk[idx-1], dbVpkpk[idx]

# Linear fit: y = m*x + b
m, b = np.polyfit([x1, x2], [y1, y2], 1)

# Solve for frequency at -3 dB
hz_3db = (target_db - b) / m

plt.plot(Hz, dbVpkpk, '-o', markersize=5, linewidth=2)

# Mark -3 dB point
plt.axvline(
    hz_3db,
    linestyle='--',
    linewidth=1.5,
    color='red',
    label=f'-3 dB @ {hz_3db:.1f} Hz'
)

plt.legend()

plt.title('SBCM Chain-B Bandwidth Measurement')
plt.xlabel("Frequency (Hz)")
plt.ylabel("Amplitude (dB)")
plt.grid(True)
plt.pause(0.1)
bscanB_fig.savefig(fname, dpi=300, bbox_inches='tight')
sleep(1)
plt.close(bscanB_fig)


im = Image('SBCM_BandwidthB_'+year+'.png',4.7*inch,2.7*inch)
elements.append(Spacer(width=1,height=0.02*inch))
elements.append(im)

# Create Table for Chain-A Characteristic Curve Measurements:
tdata = []
rowH = []
tdata.append(['SBCM Chain-A Characteristic Curve','','','','file:  '+fccA,'','','',''])
rowH.append(0.22*inch)
tdata.append(['SetPnt\n(mVpp)','Filter\n(mV)','Sigma\n(mV)','SetPnt\n(mVpp)','Filter\n(mV)','Sigma\n(mV)','SetPnt\n(mVpp)','Filter\n(mV)','Sigma\n(mV)'])
rowH.append(0.4*inch)
colW = [0.6*inch,0.8*inch,0.6*inch,0.6*inch,0.8*inch,0.6*inch,0.6*inch,0.8*inch,0.6*inch]

with open(fccA) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]
RF=np.zeros(111)
A =np.zeros(111)
S =np.zeros(111)
for i in range(0,37):
    Z = L[i].split(',')
    RF[i] = 1000*float(Z[0])
    A[i] = float(Z[1])
    S[i] = float(Z[2])
    W = L[i+37].split(',')
    RF[i+37] = 1000*float(W[0])
    A[i+37] = float(W[1])
    S[i+37] = float(W[2])   
    Y = L[i+74].split(',')
    RF[i+74] = 1000*float(Y[0])
    A[i+74] = float(Y[1])
    S[i+74] = float(Y[2]) 
    tdata.append([int(RF[i]),round(A[i],2),round(S[i],4),int(RF[i+37]),round(A[i+37],2),round(S[i+37],4),
                  int(RF[i+74]),round(A[i+74],2),round(S[i+74],4)])
    rowH.append(0.22*inch)
    
tdata.append(['SetPnt:  Rf Source Level Setting in mVpp','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filter:  Average of 16 DMM measurements of the Filter Output from the Rectifier Module','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Sigma:  The Standard Deviation of the 16 DMM Filter measurements','','','','','','','',''])
rowH.append(0.22*inch)

elements.append(PageBreak())     
t2=Table(tdata,colWidths=colW,rowHeights=rowH,style=[
                ('SPAN',(0,0),(3,0)),
                ('SPAN',(4,0),(8,0)),
                ('BACKGROUND',(0,0),(8,0),colors.lemonchiffon),
                ('BACKGROUND',(0,1),(0,38),colors.lightblue),
                ('BACKGROUND',(3,1),(3,38),colors.lightblue),
                ('BACKGROUND',(6,1),(6,38),colors.lightblue),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('LINEABOVE',(0,1),(8,1),2,colors.black),
                ('LINEABOVE',(0,2),(8,2),1.5,colors.black),
                ('LINEBEFORE',(1,1),(1,38),1.5,colors.black),
                ('LINEBEFORE',(3,1),(3,38),2,colors.black),
                ('LINEBEFORE',(4,0),(4,38),1.5,colors.black),
                ('LINEBEFORE',(6,1),(6,38),2,colors.black),
                ('LINEBEFORE',(7,1),(7,38),1.5,colors.black),
                ('SPAN',(0,39),(8,39)),
                ('SPAN',(0,40),(8,40)),
                ('SPAN',(0,41),(8,41)),
                ('LINEABOVE',(0,39),(8,39),1.5,colors.black),
                ('BACKGROUND',(0,39),(8,41),colors.lemonchiffon),
                ])

elements.append(t2)

# Analyze Data Chain-A Characteristic Curve:

fa,ax = plt.subplots(2,1,figsize=(6,9))

m,b = np.polyfit(RF[0:100],A[0:100],1)
correlation_matrix = np.corrcoef(RF[0:100],A[0:100])
p = correlation_matrix[0, 1]

Acalc=[]
for i in range(0,100):
    Acalc.append(m*RF[i]+b)

ax[0].plot(RF,A,'-o',markersize=5,linewidth=3,label='Data')
ax[0].plot(RF[0:100],Acalc,'-o',markersize=2,linewidth=1,label='Fit')
ax[0].set_title('SBCM Chain A Characteristic Curve')
ax[0].grid(True)
ax[0].set_xlabel('RF Level @ 499.68MHz (mV)')
ax[0].set_ylabel('Average Rectifier Filter Output (mV)')
ax[0].text(0.05, 0.95, "Slope: "+str(round(m,5))+"mVa/mVrf",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.86, "Intercept: "+str(round(b,4))+"mVa",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.77, "Correlation: "+str(round(p,6)),transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)  
if(p>0.99):
    ax[0].text(0.05, 0.68, "Correlation>0.99?: PASS",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[0].text(0.05, 0.68, "Correlation>0.99?: FAIL",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
mess = 'Each point is the average of the 16\nconsecutive measurements taken at\n'
mess = mess+'each RF Level setting.  The fit is\nperformed for RF settings between\n5mVpp and 500mVpp'
ax[0].text(0.44, 0.44,mess,transform=ax[0].transAxes, fontsize=10,verticalalignment='top', bbox=props)
ax[0].legend(loc='lower right')

ax[1].plot(RF,S,'-o',markersize=3,linewidth=1,label='Data')
ax[1].grid(True)
ax[1].set_xlabel('RF Level @ 499.68MHz (mV)')
ax[1].set_ylabel('Sigma for Filter Output Average (mV)')
mess = 'Each point is the standard\ndeviation of the 16 measurements\n'
mess = mess+'used to calculate the average\nFilter Output for each\nRF level setting shown above'
ax[1].text(0.01, 0.98,mess,transform=ax[1].transAxes, fontsize=10,verticalalignment='top', bbox=props)
if(max(S)<4.0):
    ax[1].text(0.05, 0.68, "max(Sigma)<4.0?: PASS",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[1].text(0.05, 0.68, "max(Sigma)<4.0?: FAIL",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
plt.pause(0.1)
fa.savefig('SBCM_CharCurveA_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_CharCurveA_'+year+'.png',6*inch,9*inch)
elements.append(im)

# Create Table for Chain-B Characteristic Curve Measurements:
tdata = []
rowH = []
tdata.append(['SBCM Chain-B Characteristic Curve','','','','file:  '+fccB,'','','',''])
rowH.append(0.22*inch)
tdata.append(['SetPnt\n(mV)','Filter\n(mV)','Sigma\n(mV)','SetPnt\n(mV)','Filter\n(mV)','Sigma\n(mV)','SetPnt\n(mV)','Filter\n(mV)','Sigma\n(mV)'])
rowH.append(0.4*inch)
colW = [0.6*inch,0.8*inch,0.6*inch,0.6*inch,0.8*inch,0.6*inch,0.6*inch,0.8*inch,0.6*inch]

with open(fccB) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]
RF=np.zeros(111)
B =np.zeros(111)
S =np.zeros(111)
for i in range(0,37):
    Z = L[i].split(',')
    RF[i] = 1000*float(Z[0])
    B[i] = float(Z[1])
    S[i] = float(Z[2])
    W = L[i+37].split(',')
    RF[i+37] = 1000*float(W[0])
    B[i+37] = float(W[1])
    S[i+37] = float(W[2])   
    Y = L[i+74].split(',')
    RF[i+74] = 1000*float(Y[0])
    B[i+74] = float(Y[1])
    S[i+74] = float(Y[2]) 
    tdata.append([int(RF[i]),round(B[i],2),round(S[i],4),int(RF[i+37]),round(B[i+37],2),round(S[i+37],4),
                  int(RF[i+74]),round(B[i+74],2),round(S[i+74],4)])
    rowH.append(0.22*inch)

tdata.append(['SetPnt:  Rf Source Level Setting in mVpp','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filter:  Average of 16 DMM measurements of the Filter Output from the Rectifier Module','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Sigma:  The Standard Deviation of the 16 DMM Filter measurements','','','','','','','',''])
rowH.append(0.22*inch)

elements.append(PageBreak())     
t2=Table(tdata,colWidths=colW,rowHeights=rowH,style=[
                ('SPAN',(0,0),(3,0)),
                ('SPAN',(4,0),(8,0)),
                ('BACKGROUND',(0,0),(8,0),colors.lemonchiffon),
                ('BACKGROUND',(0,1),(0,38),colors.lightblue),
                ('BACKGROUND',(3,1),(3,38),colors.lightblue),
                ('BACKGROUND',(6,1),(6,38),colors.lightblue),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('LINEABOVE',(0,1),(8,1),2,colors.black),
                ('LINEABOVE',(0,2),(8,2),1.5,colors.black),
                ('LINEBEFORE',(1,1),(1,38),1.5,colors.black),
                ('LINEBEFORE',(3,1),(3,38),2,colors.black),
                ('LINEBEFORE',(4,0),(4,38),1.5,colors.black),
                ('LINEBEFORE',(6,1),(6,38),2,colors.black),
                ('LINEBEFORE',(7,1),(7,38),1.5,colors.black),
                ('SPAN',(0,39),(8,39)),
                ('SPAN',(0,40),(8,40)),
                ('SPAN',(0,41),(8,41)),
                ('LINEABOVE',(0,39),(8,39),1.5,colors.black),
                ('BACKGROUND',(0,39),(8,41),colors.lemonchiffon),
                ])

elements.append(t2)

# Analyze Data Chain-B Characteristic Curve:

fa,ax = plt.subplots(2,1,figsize=(6,9))

m,b = np.polyfit(RF[0:100],B[0:100],1)
correlation_matrix = np.corrcoef(RF[0:100],B[0:100])
p = correlation_matrix[0, 1]

Bcalc=[]
for i in range(0,100):
    Bcalc.append(m*RF[i]+b)

ax[0].plot(RF,B,'-o',markersize=5,linewidth=3,label='Data')
ax[0].plot(RF[0:100],Bcalc,'-o',markersize=2,linewidth=1,label='Fit')
ax[0].set_title('SBCM Chain B Characteristic Curve')
ax[0].grid(True)
ax[0].set_xlabel('RF Level @ 499.68MHz (mV)')
ax[0].set_ylabel('Average Rectifier Filter Output (mV)')
ax[0].text(0.05, 0.95, "Slope: "+str(round(m,5))+"mVa/mVrf",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.86, "Intercept: "+str(round(b,4))+"mVa",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.77, "Correlation: "+str(round(p,6)),transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)  
if(p>0.99):
    ax[0].text(0.05, 0.68, "Correlation>0.99?: PASS",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[0].text(0.05, 0.68, "Correlation>0.99?: FAIL",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
mess = 'Each point is the average of the 16\nconsecutive measurements taken at\n'
mess = mess+'each RF Level setting.  The fit is\nperformed for RF settings between\n5mVpp and 500mVpp'
ax[0].text(0.44, 0.44,mess,transform=ax[0].transAxes, fontsize=10,verticalalignment='top', bbox=props)
ax[0].legend(loc='lower right')
ax[1].plot(RF,S,'-o',markersize=3,linewidth=1,label='Data')
ax[1].grid(True)
ax[1].set_xlabel('RF Level @ 499.68MHz (mV)')
ax[1].set_ylabel('Sigma for Filter Output Average (mV)')
mess = 'Each point is the standard\ndeviation of the 16 measurements\n'
mess = mess+'used to calculate the average\nFilter Output for each\nRF level setting shown above'
ax[1].text(0.01, 0.98,mess,transform=ax[1].transAxes, fontsize=10,verticalalignment='top', bbox=props)
if(max(S)<4.0):
    ax[1].text(0.05, 0.68, "max(Sigma)<4.0?: PASS",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[1].text(0.05, 0.68, "max(Sigma)<4.0?: FAIL",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
plt.pause(0.1)
fa.savefig('SBCM_CharCurveB_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_CharCurveB_'+year+'.png',6*inch,9*inch)
elements.append(im)
        
# Create Table for Beam Scan with 90% Fill Pattern:
tdata = []
rowH = []
tdata.append(['SBCM Beam Scan with 90% Fill','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['file:  '+fbm90,'','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['SR Beam\nPLC(mA)','Chain-A\nFilter(mV)','Chain-B\nFilter(mV)',
              'SR Beam\nPLC(mA)','Chain-A\nFilter(mV)','Chain-B\nFilter(mV)',
              'SR Beam\nPLC(mA)','Chain-A\nFilter(mV)','Chain-B\nFilter(mV)',])
rowH.append(0.4*inch)

with open(fbm90) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]

N = int(len(L))

target = 81.0
A=[]
B=[]
I=[]
i=0
while(target>27):
    Z = L[i].split(',')
    i=i+1
    if(float(Z[2])<=target):
        A.append(float(Z[0]))
        B.append(float(Z[1]))
        I.append(float(Z[2]))
        target = target - 0.5
        
N = int(len(A)/3)           
for i in range(0,N):
    dat = [str(round(I[i],2)),str(round(A[i],2)),str(round(B[i],2)),
           str(round(I[N+i],2)),str(round(A[N+i],2)),str(round(B[N+i],2)),
           str(round(I[2*N+i],2)),str(round(A[2*N+i],2)),str(round(B[2*N+i],2))]
    tdata.append(dat)
    rowH.append(0.22*inch)

tdata.append(['SR Beam PLC:  EPS PLC Measurement of Stored Beam Intensity','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filter ChainA:  DMM measurement of Output from Chain-A Rectifier Module','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filter ChainB:  DMM measurement of Output from Chain-B Rectifier Module','','','','','','','',''])
rowH.append(0.22*inch)

elements.append(PageBreak())     
t2=Table(tdata,0.75*inch,rowHeights=rowH,style=[
                ('SPAN',(0,0),(8,0)),
                ('SPAN',(0,1),(8,1)),
                ('BACKGROUND',(0,0),(8,1),colors.lemonchiffon),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('LINEABOVE',(0,1),(8,1),2,colors.black),
                ('LINEABOVE',(0,2),(8,2),2,colors.black),
                ('LINEABOVE',(0,3),(8,3),2,colors.black),
                ('LINEBEFORE',(3,1),(3,38),2,colors.black),
                ('LINEBEFORE',(6,1),(6,38),2,colors.black),
                ('LINEABOVE',(0,39),(8,39),2,colors.black),
                ('SPAN',(0,39),(8,39)),
                ('SPAN',(0,40),(8,40)),
                ('SPAN',(0,41),(8,41)),
                ('BACKGROUND',(0,39),(8,41),colors.lemonchiffon),
                ])

elements.append(t2)

# Analyze Data for 90% Fill Pattern Beam Scan:

fa,ax = plt.subplots(2,1,figsize=(6,9))

m,b = np.polyfit(A,I,1)
correlation_matrix = np.corrcoef(A,I)
p = correlation_matrix[0, 1]

Icalc=[]
for i in range(0,len(A)):
    Icalc.append(m*A[i]+b)

ax[0].plot(A,I,'-o',markersize=5,linewidth=3,label='Data')
ax[0].plot(A,Icalc,'-o',markersize=2,linewidth=1,label='Fit')
ax[0].set_title('EPS PLC Beam Current vs Filter Voltage for 90% Fill Pattern')
ax[0].grid(True)
ax[0].set_xlabel('Chain-A Filter Measurement (mV)')
ax[0].set_ylabel('EPS PLC Beam Current Measurement (mA)')
ax[0].text(0.05, 0.95, "Slope: "+str(round(m,5))+"mA/mV",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.86, "Intercept: "+str(round(b,4))+"mA",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.77, "Correlation: "+str(round(p,6)),transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)  
if(p>0.99):
    ax[0].text(0.05, 0.68, "Correlation>0.99?: PASS",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[0].text(0.05, 0.68, "Correlation>0.99?: FAIL",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
ymin,ymax=ax[0].get_ylim()
xmin,xmax=ax[0].get_xlim()
Vtoss = 1010  #Determined by Engineer for Chain A
Itoss = m*Vtoss + b #mA , determined by Fit
ax[0].autoscale(enable=False,axis='both')
ax[0].plot([xmin,Vtoss,Vtoss],[Itoss,Itoss,ymin],'--o',color='black',markersize=6,markerfacecolor='red',
           markeredgecolor='black',linewidth=2,label='TOSS')
ax[0].text(0.62, 0.45, "90% Fill Pattern\nThreshold: "+str(Vtoss)+'mV\nI(Thres): '+str(round(Itoss,2))+'mA',transform=ax[0].transAxes,
           fontsize=12,verticalalignment='top', bbox=props) 
ax[0].legend(loc='lower right')

m,b = np.polyfit(B,I,1)
correlation_matrix = np.corrcoef(B,I)
p = correlation_matrix[0, 1]

Icalc=[]
for i in range(0,len(B)):
    Icalc.append(m*B[i]+b)
    
ax[1].plot(B,I,'-o',markersize=5,linewidth=3,label='Data')
ax[1].plot(B,Icalc,'-o',markersize=2,linewidth=1,label='Fit')
ax[1].grid(True)
ax[1].set_xlabel('Chain-B Filter Measurement (mV)')
ax[1].set_ylabel('EPS PLC Beam Current Measurement (mA)')
ax[1].text(0.05, 0.95, "Slope: "+str(round(m,5))+"mA/mV",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[1].text(0.05, 0.86, "Intercept: "+str(round(b,4))+"mA",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[1].text(0.05, 0.77, "Correlation: "+str(round(p,6)),transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=props)   
if(p>0.99):
    ax[1].text(0.05, 0.68, "Correlation>0.99?: PASS",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[1].text(0.05, 0.68, "Correlation>0.99?: FAIL",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
ymin,ymax=ax[1].get_ylim()
xmin,xmax=ax[1].get_xlim()
Vtoss = 1010  #Determined by Engineer for Chain B
Itoss = m*Vtoss + b #mA , determined by Fit
ax[1].autoscale(enable=False,axis='both')
ax[1].plot([xmin,Vtoss,Vtoss],[Itoss,Itoss,ymin],'--o',color='black',markersize=6,markerfacecolor='red',
           markeredgecolor='black',linewidth=2,label='TOSS')
ax[1].text(0.62, 0.45, "90% Fill Pattern\nThreshold: "+str(Vtoss)+'mV\nI(Thres): '+str(round(Itoss,2))+'mA',transform=ax[1].transAxes,
           fontsize=12,verticalalignment='top', bbox=props) 
ax[1].legend(loc='lower right')
plt.pause(0.1)
fa.savefig('SBCM_90pctFill_BeamScan_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_90pctFill_BeamScan_'+year+'.png',6*inch,9*inch)
elements.append(im)

# Create Table for Beam Scan with 20% Fill Pattern:
tdata = []
rowH = []
tdata.append(['SBCM Beam Scan with 20% Fill','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['file:  '+fbm20,'','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['SR Beam\nPLC(mA)','Chain-A\nFilter(mV)','Chain-B\nFilter(mV)',
              'SR Beam\nPLC(mA)','Chain-A\nFilter(mV)','Chain-B\nFilter(mV)',
              'SR Beam\nPLC(mA)','Chain-A\nFilter(mV)','Chain-B\nFilter(mV)',])
rowH.append(0.4*inch)

with open(fbm20) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]

N = int(len(L))

target = 77.0
A=[]
B=[]
I=[]
i=0
while(target>23):
    Z = L[i].split(',')
    i=i+1
    if(float(Z[2])<=target):
        A.append(float(Z[0]))
        B.append(float(Z[1]))
        I.append(float(Z[2]))
        target = target - 0.5
N = int(len(A)/3)           
for i in range(0,N):
    dat = [str(round(I[i],2)),str(round(A[i],2)),str(round(B[i],2)),
           str(round(I[N+i],2)),str(round(A[N+i],2)),str(round(B[N+i],2)),
           str(round(I[2*N+i],2)),str(round(A[2*N+i],2)),str(round(B[2*N+i],2))]
    tdata.append(dat)
    rowH.append(0.22*inch)

tdata.append(['SR Beam PLC:  EPS PLC Measurement of Stored Beam Intensity','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filter ChainA:  DMM measurement of Output from Chain-A Rectifier Module','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filter ChainB:  DMM measurement of Output from Chain-B Rectifier Module','','','','','','','',''])
rowH.append(0.22*inch)


elements.append(PageBreak())     
t2=Table(tdata,0.75*inch,rowHeights=rowH,style=[
                ('SPAN',(0,0),(8,0)),
                ('SPAN',(0,1),(8,1)),
                ('BACKGROUND',(0,0),(8,1),colors.lemonchiffon),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('LINEABOVE',(0,1),(8,1),2,colors.black),
                ('LINEABOVE',(0,2),(8,2),2,colors.black),
                ('LINEABOVE',(0,3),(8,3),2,colors.black),
                ('LINEBEFORE',(3,1),(3,38),2,colors.black),
                ('LINEBEFORE',(6,1),(6,38),2,colors.black),
                ('LINEABOVE',(0,39),(8,39),2,colors.black),
                ('SPAN',(0,39),(8,39)),
                ('SPAN',(0,40),(8,40)),
                ('SPAN',(0,41),(8,41)),
                ('BACKGROUND',(0,39),(8,41),colors.lemonchiffon),
                ])
elements.append(t2)

# Analyze Data for 20% Fill Pattern Beam Scan:

fa,ax = plt.subplots(2,1,figsize=(6,9))

m,b = np.polyfit(A,I,1)
correlation_matrix = np.corrcoef(A,I)
p = correlation_matrix[0, 1]

Icalc=[]
for i in range(0,len(A)):
    Icalc.append(m*A[i]+b)

ax[0].plot(A,I,'-o',markersize=5,linewidth=3,label='Data')
ax[0].plot(A,Icalc,'-o',markersize=2,linewidth=1,label='Fit')
ax[0].set_title('EPS PLC Beam Current vs Filter Voltage for 20% Fill Pattern')
ax[0].grid(True)
ax[0].set_xlabel('Chain-A Filter Measurement (mV)')
ax[0].set_ylabel('EPS PLC Beam Current Measurement (mA)')
ax[0].text(0.05, 0.95, "Slope: "+str(round(m,5))+"mA/mV",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.86, "Intercept: "+str(round(b,4))+"mA",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[0].text(0.05, 0.77, "Correlation: "+str(round(p,6)),transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=props)  
if(p>0.99):
    ax[0].text(0.05, 0.68, "Correlation>0.99?: PASS",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[0].text(0.05, 0.68, "Correlation>0.99?: FAIL",transform=ax[0].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
ymin,ymax=ax[0].get_ylim()
xmin,xmax=ax[0].get_xlim()
Vtoss = 1010  #Determined by Engineer for Chain A
Itoss = m*Vtoss + b #mA , determined by Fit
ax[0].autoscale(enable=False,axis='both')
ax[0].plot([xmin,Vtoss,Vtoss],[Itoss,Itoss,ymin],'--o',color='black',markersize=6,markerfacecolor='red',
           markeredgecolor='black',linewidth=2,label='TOSS')
ax[0].text(0.62, 0.45, "20% Fill Pattern\nThreshold: "+str(Vtoss)+'mV\nI(Thres): '+str(round(Itoss,2))+'mA',transform=ax[0].transAxes,
           fontsize=12,verticalalignment='top', bbox=props) 
ax[0].legend(loc='lower right')

m,b = np.polyfit(B,I,1)
correlation_matrix = np.corrcoef(B,I)
p = correlation_matrix[0, 1]

Icalc=[]
for i in range(0,len(B)):
    Icalc.append(m*B[i]+b)
    
ax[1].plot(B,I,'-o',markersize=5,linewidth=3,label='Data')
ax[1].plot(B,Icalc,'-o',markersize=2,linewidth=1,label='Fit')
ax[1].grid(True)
ax[1].set_xlabel('Chain-B Filter Measurement (mV)')
ax[1].set_ylabel('EPS PLC Beam Current Measurement (mA)')
ax[1].text(0.05, 0.95, "Slope: "+str(round(m,5))+"mA/mV",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[1].text(0.05, 0.86, "Intercept: "+str(round(b,4))+"mA",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=props)
ax[1].text(0.05, 0.77, "Correlation: "+str(round(p,6)),transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=props)   
if(p>0.99):
    ax[1].text(0.05, 0.68, "Correlation>0.99?: PASS",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=good)
else:
    ax[1].text(0.05, 0.68, "Correlation>0.99?: FAIL",transform=ax[1].transAxes, fontsize=12,verticalalignment='top', bbox=bad)
ymin,ymax=ax[1].get_ylim()
xmin,xmax=ax[1].get_xlim()
Vtoss = 1010  #Determined by Engineer for Chain B
Itoss = m*Vtoss + b #mA , determined by Fit
ax[1].autoscale(enable=False,axis='both')
ax[1].plot([xmin,Vtoss,Vtoss],[Itoss,Itoss,ymin],'--o',color='black',markersize=6,markerfacecolor='red',
           markeredgecolor='black',linewidth=2,label='TOSS')
ax[1].text(0.62, 0.45, "20% Fill Pattern\nThreshold: "+str(Vtoss)+'mV\nI(Thres): '+str(round(Itoss,2))+'mA',transform=ax[1].transAxes,
           fontsize=12,verticalalignment='top', bbox=props) 
ax[1].legend(loc='lower right')
plt.pause(0.1)
fa.savefig('SBCM_20pctFill_BeamScan_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_20pctFill_BeamScan_'+year+'.png',6*inch,9*inch)
elements.append(im)

tdata=[]
tdata.append(['Based on the data shown above the following changes were made:'])
tdata.append(['I(TOSS) = 54mA for a 20% Fill Pattern'])
tdata.append(['Chain-A Threshold set to 1010mV'])
tdata.append(['Chain-B Threshold set to 1010mV'])
   
t2=Table(tdata,5*inch,0.22*inch,style=[
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ('BACKGROUND',(0,0),(-1,-1),colors.lemonchiffon),
                ('GRID',(0,0),(-1,-1),0.5,colors.black),
                ])
elements.append(t2)

# Create Table for Functional Test with 20% Fill Pattern and Beam Increasing:
tdata = []
rowH = []
tdata.append(['SBCM Functional Scan with 20% Fill and Increasing Beam','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['file:  '+fbm20,'','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'
              ,'','Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'])
rowH.append(0.4*inch)

with open(ftestR20) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]
N = int(len(L))
WDTA20R=[0,0]
COMA20R=[0,0]
RELA20R=[0,0]
WDTB20R=[0,0]
COMB20R=[0,0]
RELB20R=[0,0]
AW=[]
BW=[]
IW=[]
WAW=[]
CAW=[]
RAW=[]
WBW=[]
CBW=[]
RBW=[]
target = 0.0
for i in range(start,N-end_cut):
    tag=0
    Z = L[i].split(',')
    I=float(Z[0])
    A=float(Z[1])
    B=float(Z[2])
    WA=int(Z[3])
    CA=int(Z[4])
    RA=int(Z[5])
    WB=int(Z[6])
    CB=int(Z[7])
    RB=int(Z[8])
    if(I > target):
        tag=1
        target = target + 1
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTA20R[0]==0 and WA==1 and tag==0):
        tag = 1
        WDTA20R[0] = I
        WDTA20R[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTB20R[0]==0 and WB==1 and tag==0):
        tag = 1
        WDTB20R[0] = I
        WDTB20R[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMA20R[0]==0 and CA==2 and tag==0):
        tag = 1
        COMA20R[0] = I
        COMA20R[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMB20R[0]==0 and CB==2 and tag==0):
        tag = 1
        COMB20R[0] = I
        COMB20R[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELA20R[0]==0 and RA==3 and tag==0):
        tag = 1
        RELA20R[0] = I
        RELA20R[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELB20R[0]==0 and RB==3 and tag==0):
        tag = 1
        RELB20R[0] = I
        RELB20R[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)

N = int(len(AW)/2)           
for i in range(0,N):
    dat = [str(round(IW[i],2)),str(round(AW[i],2)),str(WAW[i])+','+str(CAW[i])+','+str(RAW[i]),
           str(round(BW[i],2)),str(WBW[i])+','+str(CBW[i])+','+str(RBW[i]),'',
           str(round(IW[N+i],2)),str(round(AW[N+i],2)),str(WAW[N+i])+','+str(CAW[N+i])+','+str(RAW[N+i]),
           str(round(BW[N+i],2)),str(WBW[N+i])+','+str(CBW[N+i])+','+str(RBW[N+i])]                                                                                    
    tdata.append(dat)
    rowH.append(0.22*inch)  
tdata.append(['Beam: Storage Ring Beam as Measured by the EPS PLC Chassis in mA','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filt-A: Chain-A Rectifier Module Filter Output Measured by the Keithley 2100 in mV','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Bits-A: Chain-A State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filt-B: Chain-B Rectifier Module Filter Output Measured by the Keithley 2100 in mV','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Bits-B: Chain-B State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC','','','','','','','','','',''])
rowH.append(0.22*inch)
colW = [0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch,0.07*inch,0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch]
elements.append(PageBreak())     
nrows = len(tdata)
footer_start = nrows - 5
footer_end = nrows - 1

table_style = [
    ('SPAN',(0,0),(10,0)),
    ('SPAN',(0,1),(10,1)),
    ('BACKGROUND',(0,0),(10,1),colors.lemonchiffon),

    ('GRID',(0,0),(-1,-1),0.5,colors.black),
    ('BOX',(0,0),(-1,-1),2,colors.black),

    ('LINEABOVE',(0,1),(10,1),2,colors.black),
    ('LINEABOVE',(0,2),(10,2),2,colors.black),
    ('LINEABOVE',(0,3),(10,3),2,colors.black),
]

# Footer styling (SAFE)
for r in range(footer_start, footer_end + 1):
    table_style.append(('SPAN', (0, r), (10, r)))
    table_style.append(('BACKGROUND', (0, r), (10, r), colors.lemonchiffon))

table_style.append(('LINEABOVE',(0, footer_start),(10, footer_start),2,colors.black))
t2 = Table(
    tdata,
    colWidths=colW,
    rowHeights=rowH,
    style=table_style
)
elements.append(t2)

fa,ax = plt.subplots(2,1,figsize=(7,9))
ax02 = ax[0].twinx()
ax12 = ax[1].twinx()

ax[0].plot(IW,'-o',color='blue')
ax[0].grid(True)
ax[0].set_xlabel("Time (AU)")
ax[0].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[0].set_title("SBCM-A 20% Fill Functional Test")
ax[0].tick_params(axis='y', labelcolor='blue')
ax02.plot(WAW,'-o',color='red')
ax02.plot(CAW,'-o',color='green')
ax02.plot(RAW,'-o',color='black')
ax02.set_ylabel("SBCM-A Status Bits",color='black')
ax02.set_yticks([0,1,2,3,4,5])
ax02.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT ON: Beam="+str(round(WDTA20R[0],2))+"mA  SBCM="+str(round(WDTA20R[1],1))+"mV"
ax02.text(0.05, 0.96,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP ON: Beam="+str(round(COMA20R[0],2))+"mA  SBCM="+str(round(COMA20R[1],1))+"mV"
ax02.text(0.05, 0.89,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELA20R[0]<50.0):
    line = "RELAY ON: Beam="+str(round(RELA20R[0],2))+"mA  SBCM="+str(round(RELA20R[1],1))+"mV\n"
    line = line+"RELAY ON Beam > 50.0 ? FAIL"
    ax02.text(0.05, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY ON: Beam="+str(round(RELA20R[0],2))+"mA  SBCM="+str(round(RELA20R[1],1))+"mV\n"
    line = line+"RELAY ON Beam > 50.0 ? PASS"
    ax02.text(0.05, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=good)
ax[1].plot(IW,'-o',color='blue')
ax[1].grid(True)
ax[1].set_xlabel("Time (AU)")
ax[1].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[1].tick_params(axis='y', labelcolor='blue')
ax12.plot(WBW,'-o',color='red')
ax12.plot(CBW,'-o',color='green')
ax12.plot(RBW,'-o',color='black')
ax12.set_ylabel("SBCM-B Status Bits",color='black')
ax[1].set_title("SBCM-B 20% Fill Functional Test")
ax12.set_yticks([0,1,2,3,4,5])
ax12.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT ON: Beam="+str(round(WDTB20R[0],2))+"mA  SBCM="+str(round(WDTB20R[1],1))+"mV"
ax12.text(0.05, 0.96,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP ON: Beam="+str(round(COMB20R[0],2))+"mA  SBCM="+str(round(COMB20R[1],1))+"mV"
ax12.text(0.05, 0.89,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELB20R[0]<50.0):
    line = "RELAY ON: Beam="+str(round(RELB20R[0],2))+"mA  SBCM="+str(round(RELB20R[1],1))+"mV\n"
    line = line+"RELAY ON Beam > 50.0 ? FAIL"
    ax12.text(0.05, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY ON: Beam="+str(round(RELB20R[0],2))+"mA  SBCM="+str(round(RELB20R[1],1))+"mV\n"
    line = line+"RELAY ON Beam > 50.0 ? PASS"
    ax12.text(0.05, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=good)

plt.tight_layout()
plt.pause(0.1)
plt.pause(0.1)
fa.savefig('SBCM_20pctFillBeamRisingFunctTest_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_20pctFillBeamRisingFunctTest_'+year+'.png',7*inch,9*inch)
elements.append(im)

# Create Table for Functional Test with 20% Fill Pattern and Beam Decreasing:
tdata = []
rowH = []
tdata.append(['SBCM Functional Scan with 20% Fill and Decreasing Beam','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['file:  '+ftestF20,'','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'
              ,'','Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'])
rowH.append(0.4*inch)

with open(ftestF20) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]
N = int(len(L))
WDTA20F=[0,0]
COMA20F=[0,0]
RELA20F=[0,0]
WDTB20F=[0,0]
COMB20F=[0,0]
RELB20F=[0,0]
AW=[]
BW=[]
IW=[]
WAW=[]
CAW=[]
RAW=[]
WBW=[]
CBW=[]
RBW=[]
target = 60.0
for i in range(start,N-end_cut):
    Z = L[i].split(',')
    I=float(Z[0])
    A=float(Z[1])
    B=float(Z[2])
    WA=int(Z[3])
    CA=int(Z[4])
    RA=int(Z[5])
    WB=int(Z[6])
    CB=int(Z[7])
    RB=int(Z[8])
    if(I < target):
        if((target-1)<I):
            target = target - 1
        else:
            target = I - 1
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTA20F[0]==0 and WA==0):
        WDTA20F[0] = I
        WDTA20F[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTB20F[0]==0 and WB==0):
        WDTB20F[0] = I
        WDTB20F[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMA20F[0]==0 and CA==0):
        COMA20F[0] = I
        COMA20F[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMB20F[0]==0 and CB==0):
        COMB20F[0] = I
        COMB20F[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELA20F[0]==0 and RA==0):
        RELA20F[0] = I
        RELA20F[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELB20F[0]==0 and RB==0):
        RELB20F[0] = I
        RELB20F[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)

N = int(len(AW)/2)           
for i in range(0,N):
    dat = [str(round(IW[i],2)),str(round(AW[i],2)),str(WAW[i])+','+str(CAW[i])+','+str(RAW[i]),
           str(round(BW[i],2)),str(WBW[i])+','+str(CBW[i])+','+str(RBW[i]),'',
           str(round(IW[N+i],2)),str(round(AW[N+i],2)),str(WAW[N+i])+','+str(CAW[N+i])+','+str(RAW[N+i]),
           str(round(BW[N+i],2)),str(WBW[N+i])+','+str(CBW[N+i])+','+str(RBW[N+i])]                                                                                    
    tdata.append(dat)
    rowH.append(0.22*inch)  
tdata.append(['Beam: Storage Ring Beam as Measured by the EPS PLC Chassis in mA','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filt-A: Chain-A Rectifier Module Filter Output Measured by the Keithley 2100 in mV','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Bits-A: Chain-A State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filt-B: Chain-B Rectifier Module Filter Output Measured by the Keithley 2100 in mV','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Bits-B: Chain-B State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC','','','','','','','','','',''])
rowH.append(0.22*inch)
colW = [0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch,0.07*inch,0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch]
elements.append(PageBreak())     
nrows = len(tdata)
footer_start = nrows - 5
footer_end = nrows - 1

table_style = [
    ('SPAN',(0,0),(10,0)),
    ('SPAN',(0,1),(10,1)),
    ('BACKGROUND',(0,0),(10,1),colors.lemonchiffon),

    ('GRID',(0,0),(-1,-1),0.5,colors.black),
    ('BOX',(0,0),(-1,-1),2,colors.black),

    ('LINEABOVE',(0,1),(10,1),2,colors.black),
    ('LINEABOVE',(0,2),(10,2),2,colors.black),
    ('LINEABOVE',(0,3),(10,3),2,colors.black),
]

# Footer styling (SAFE)
for r in range(footer_start, footer_end + 1):
    table_style.append(('SPAN', (0, r), (10, r)))
    table_style.append(('BACKGROUND', (0, r), (10, r), colors.lemonchiffon))

table_style.append(('LINEABOVE',(0, footer_start),(10, footer_start),2,colors.black))
t2 = Table(
    tdata,
    colWidths=colW,
    rowHeights=rowH,
    style=table_style
)
elements.append(t2)

fa,ax = plt.subplots(2,1,figsize=(7,9))
ax02 = ax[0].twinx()
ax12 = ax[1].twinx()

ax[0].plot(IW,'-o',color='blue')
ax[0].grid(True)
ax[0].set_xlabel("Time (AU)")
ax[0].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[0].set_title("SBCM-A 20% Fill Functional Test")
ax[0].tick_params(axis='y', labelcolor='blue')
ax02.plot(WAW,'-o',color='red')
ax02.plot(CAW,'-o',color='green')
ax02.plot(RAW,'-o',color='black')
ax02.set_ylabel("SBCM-A Status Bits",color='black')
ax02.set_yticks([0,1,2,3,4,5])
ax02.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT OFF: Beam="+str(round(WDTA20F[0],2))+"mA  SBCM="+str(round(WDTA20F[1],1))+"mV"
ax02.text(0.35, 0.96,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP OFF: Beam="+str(round(COMA20F[0],2))+"mA  SBCM="+str(round(COMA20F[1],1))+"mV"
ax02.text(0.35, 0.89,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELA20R[0]<50.0):
    line = "RELAY OFF: Beam="+str(round(RELA20F[0],2))+"mA  SBCM="+str(round(RELA20F[1],1))+"mV\n"
    line = line+"RELAY OFF Beam > 50.0 ? FAIL"
    ax02.text(0.35, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY OFF: Beam="+str(round(RELA20F[0],2))+"mA  SBCM="+str(round(RELA20F[1],1))+"mV\n"
    line = line+"RELAY OFF Beam > 50.0 ? PASS"
    ax02.text(0.35, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=good)

ax[1].plot(IW,'-o',color='blue')
ax[1].grid(True)
ax[1].set_xlabel("Time (AU)")
ax[1].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[1].tick_params(axis='y', labelcolor='blue')
ax12.plot(WBW,'-o',color='red')
ax12.plot(CBW,'-o',color='green')
ax12.plot(RBW,'-o',color='black')
ax12.set_ylabel("SBCM-B Status Bits",color='black')
ax[1].set_title("SBCM-B 20% Fill Functional Test")
ax12.set_yticks([0,1,2,3,4,5])
ax12.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT OFF: Beam="+str(round(WDTB20F[0],2))+"mA  SBCM="+str(round(WDTB20F[1],1))+"mV"
ax12.text(0.35, 0.96,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP OFF: Beam="+str(round(COMB20F[0],2))+"mA  SBCM="+str(round(COMB20F[1],1))+"mV"
ax12.text(0.35, 0.89,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELB20R[0]<50.0):
    line = "RELAY OFF: Beam="+str(round(RELB20F[0],2))+"mA  SBCM="+str(round(RELB20F[1],1))+"mV\n"
    line = line+"RELAY OFF Beam > 50.0 ? FAIL"
    ax12.text(0.35, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY OFF: Beam="+str(round(RELB20F[0],2))+"mA  SBCM="+str(round(RELB20F[1],1))+"mV\n"
    line = line+"RELAY OFF Beam > 50.0 ? PASS"
    ax12.text(0.35, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=good)

plt.tight_layout()
plt.pause(0.1)
plt.pause(0.1)
fa.savefig('SBCM_20pctFillBeamFallingFunctTest_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_20pctFillBeamFallingFunctTest_'+year+'.png',7*inch,9*inch)
elements.append(im)

# Create Table for Functional Test with 90% Fill Pattern and Beam Increasing:
tdata = []
rowH = []
tdata.append(['SBCM Functional Scan with 90% Fill and Increasing Beam','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['file:  '+ftestR90,'','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'
              ,'','Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'])
rowH.append(0.4*inch)

with open(ftestR90) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]
N = int(len(L))
WDTA90R=[0,0]
COMA90R=[0,0]
RELA90R=[0,0]
WDTB90R=[0,0]
COMB90R=[0,0]
RELB90R=[0,0]
AW=[]
BW=[]
IW=[]
WAW=[]
CAW=[]
RAW=[]
WBW=[]
CBW=[]
RBW=[]
target = 0.0
for i in range(start,N-end_cut):
    Z = L[i].split(',')
    I=float(Z[0])
    A=float(Z[1])
    B=float(Z[2])
    WA=int(Z[3])
    CA=int(Z[4])
    RA=int(Z[5])
    WB=int(Z[6])
    CB=int(Z[7])
    RB=int(Z[8])
    if(I > target):
        target = target + 1
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTA90R[0]==0 and WA==1):
        WDTA90R[0] = I
        WDTA90R[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTB90R[0]==0 and WB==1):
        WDTB90R[0] = I
        WDTB90R[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMA90R[0]==0 and CA==2):
        COMA90R[0] = I
        COMA90R[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMB90R[0]==0 and CB==2):
        COMB90R[0] = I
        COMB90R[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELA90R[0]==0 and RA==3):
        RELA90R[0] = I
        RELA90R[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELB90R[0]==0 and RB==3):
        RELB90R[0] = I
        RELB90R[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)

N = int(len(AW)/2)           
for i in range(0,N):
    dat = [str(round(IW[i],2)),str(round(AW[i],2)),str(WAW[i])+','+str(CAW[i])+','+str(RAW[i]),
           str(round(BW[i],2)),str(WBW[i])+','+str(CBW[i])+','+str(RBW[i]),'',
           str(round(IW[N+i],2)),str(round(AW[N+i],2)),str(WAW[N+i])+','+str(CAW[N+i])+','+str(RAW[N+i]),
           str(round(BW[N+i],2)),str(WBW[N+i])+','+str(CBW[N+i])+','+str(RBW[N+i])]                                                                                    
    tdata.append(dat)
    rowH.append(0.22*inch)  
tdata.append(['Beam: Storage Ring Beam as Measured by the EPS PLC Chassis in mA','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filt-A: Chain-A Rectifier Module Filter Output Measured by the Keithley 2100 in mV','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Bits-A: Chain-A State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filt-B: Chain-B Rectifier Module Filter Output Measured by the Keithley 2100 in mV','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Bits-B: Chain-B State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC','','','','','','','','','',''])
rowH.append(0.22*inch)
colW = [0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch,0.07*inch,0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch]
elements.append(PageBreak())     
nrows = len(tdata)
footer_start = nrows - 5
footer_end = nrows - 1

table_style = [
    ('SPAN',(0,0),(10,0)),
    ('SPAN',(0,1),(10,1)),
    ('BACKGROUND',(0,0),(10,1),colors.lemonchiffon),

    ('GRID',(0,0),(-1,-1),0.5,colors.black),
    ('BOX',(0,0),(-1,-1),2,colors.black),

    ('LINEABOVE',(0,1),(10,1),2,colors.black),
    ('LINEABOVE',(0,2),(10,2),2,colors.black),
    ('LINEABOVE',(0,3),(10,3),2,colors.black),
]

# Footer styling (SAFE)
for r in range(footer_start, footer_end + 1):
    table_style.append(('SPAN', (0, r), (10, r)))
    table_style.append(('BACKGROUND', (0, r), (10, r), colors.lemonchiffon))

table_style.append(('LINEABOVE',(0, footer_start),(10, footer_start),2,colors.black))
t2 = Table(
    tdata,
    colWidths=colW,
    rowHeights=rowH,
    style=table_style
)
elements.append(t2)

fa,ax = plt.subplots(2,1,figsize=(7,9))
ax02 = ax[0].twinx()
ax12 = ax[1].twinx()

ax[0].plot(IW,'-o',color='blue')
ax[0].grid(True)
ax[0].set_xlabel("Time (AU)")
ax[0].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[0].set_title("SBCM-A 90% Fill Functional Test")
ax[0].tick_params(axis='y', labelcolor='blue')
ax02.plot(WAW,'-o',color='red')
ax02.plot(CAW,'-o',color='green')
ax02.plot(RAW,'-o',color='black')
ax02.set_ylabel("SBCM-A Status Bits",color='black')
ax02.set_yticks([0,1,2,3,4,5])
ax02.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT ON: Beam="+str(round(WDTA90R[0],2))+"mA  SBCM="+str(round(WDTA90R[1],1))+"mV"
ax02.text(0.05, 0.96,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP ON: Beam="+str(round(COMA90R[0],2))+"mA  SBCM="+str(round(COMA90R[1],1))+"mV"
ax02.text(0.05, 0.89,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELA90R[0]<50.0):
    line = "RELAY ON: Beam="+str(round(RELA90R[0],2))+"mA  SBCM="+str(round(RELA90R[1],1))+"mV\n"
    line = line+"RELAY ON Beam > 50.0 ? FAIL"
    ax02.text(0.05, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY ON: Beam="+str(round(RELA90R[0],2))+"mA  SBCM="+str(round(RELA90R[1],1))+"mV\n"
    line = line+"RELAY ON Beam > 50.0 ? PASS"
    ax02.text(0.05, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=good)
ax[1].plot(IW,'-o',color='blue')
ax[1].grid(True)
ax[1].set_xlabel("Time (AU)")
ax[1].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[1].tick_params(axis='y', labelcolor='blue')
ax12.plot(WBW,'-o',color='red')
ax12.plot(CBW,'-o',color='green')
ax12.plot(RBW,'-o',color='black')
ax12.set_ylabel("SBCM-B Status Bits",color='black')
ax[1].set_title("SBCM-B 90% Fill Functional Test")
ax12.set_yticks([0,1,2,3,4,5])
ax12.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT ON: Beam="+str(round(WDTB90R[0],2))+"mA  SBCM="+str(round(WDTB90R[1],1))+"mV"
ax12.text(0.05, 0.96,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP ON: Beam="+str(round(COMB90R[0],2))+"mA  SBCM="+str(round(COMB90R[1],1))+"mV"
ax12.text(0.05, 0.89,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELB90R[0]<50.0):
    line = "RELAY ON: Beam="+str(round(RELB90R[0],2))+"mA  SBCM="+str(round(RELB90R[1],1))+"mV\n"
    line = line+"RELAY ON Beam > 50.0 ? FAIL"
    ax12.text(0.05, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY ON: Beam="+str(round(RELB90R[0],2))+"mA  SBCM="+str(round(RELB90R[1],1))+"mV\n"
    line = line+"RELAY ON Beam > 50.0 ? PASS"
    ax12.text(0.05, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=good)

plt.tight_layout()
plt.pause(0.1)
plt.pause(0.1)
fa.savefig('SBCM_90pctFillBeamRisingFunctTest_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_90pctFillBeamRisingFunctTest_'+year+'.png',7*inch,9*inch)
elements.append(im)
            
# Create Table for Functional Test with 90% Fill Pattern and Beam Decreasing:
tdata = []
rowH = []
tdata.append(['SBCM Functional Scan with 90% Fill and Decreasing Beam','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['file:  '+ftestF90,'','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'
              ,'','Beam\n(mA)','Filt-A\n(mV)','Bits-A\nW,C,R','Filt-B\n(mV)','Bits-B\nW,C,R'])
rowH.append(0.4*inch)

with open(ftestF90) as f:
    L = f.readlines()
    L = [x.strip('\n') for x in L]
N = int(len(L))
WDTA90F=[0,0]
COMA90F=[0,0]
RELA90F=[0,0]
WDTB90F=[0,0]
COMB90F=[0,0]
RELB90F=[0,0]
AW=[]
BW=[]
IW=[]
WAW=[]
CAW=[]
RAW=[]
WBW=[]
CBW=[]
RBW=[]
target = 70.0
for i in range(start,N-end_cut):
    Z = L[i].split(',')
    I=float(Z[0])
    A=float(Z[1])
    B=float(Z[2])
    WA=int(Z[3])
    CA=int(Z[4])
    RA=int(Z[5])
    WB=int(Z[6])
    CB=int(Z[7])
    RB=int(Z[8])
    if(I < target):
        if((target-1)<I):
            target = target - 1
        else:
            target = I - 1
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTA90F[0]==0 and WA==0):
        WDTA90F[0] = I
        WDTA90F[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(WDTB90F[0]==0 and WB==0):
        WDTB90F[0] = I
        WDTB90F[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMA90F[0]==0 and CA==0):
        COMA90F[0] = I
        COMA90F[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(COMB90F[0]==0 and CB==0):
        COMB90F[0] = I
        COMB90F[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELA90F[0]==0 and RA==0):
        RELA90F[0] = I
        RELA90F[1] = A
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)
    if(RELB90F[0]==0 and RB==0):
        RELB90F[0] = I
        RELB90F[1] = B
        AW.append(A)
        BW.append(B)
        IW.append(I)
        WAW.append(WA)
        CAW.append(CA)
        RAW.append(RA)
        WBW.append(WB)
        CBW.append(CB)
        RBW.append(RB)

N = int(len(AW)/2)           
for i in range(0,N):
    dat = [str(round(IW[i],2)),str(round(AW[i],2)),str(WAW[i])+','+str(CAW[i])+','+str(RAW[i]),
           str(round(BW[i],2)),str(WBW[i])+','+str(CBW[i])+','+str(RBW[i]),'',
           str(round(IW[N+i],2)),str(round(AW[N+i],2)),str(WAW[N+i])+','+str(CAW[N+i])+','+str(RAW[N+i]),
           str(round(BW[N+i],2)),str(WBW[N+i])+','+str(CBW[N+i])+','+str(RBW[N+i])]                                                                                    
    tdata.append(dat)
    rowH.append(0.22*inch)  
tdata.append(['Beam: Storage Ring Beam as Measured by the EPS PLC Chassis in mA','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filt-A: Chain-A Rectifier Module Filter Output Measured by the Keithley 2100 in mV','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Bits-A: Chain-A State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Filt-B: Chain-B Rectifier Module Filter Output Measured by the Keithley 2100 in mV','','','','','','','','','',''])
rowH.append(0.22*inch)
tdata.append(['Bits-B: Chain-B State of the WDT, Comparator, and Relay Status Bits Read From the SBCM PLC','','','','','','','','','',''])
rowH.append(0.22*inch)
colW = [0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch,0.07*inch,0.55*inch,0.65*inch,0.6*inch,0.65*inch,0.6*inch]
elements.append(PageBreak())     
nrows = len(tdata)
footer_start = nrows - 5
footer_end = nrows - 1

table_style = [
    ('SPAN',(0,0),(10,0)),
    ('SPAN',(0,1),(10,1)),
    ('BACKGROUND',(0,0),(10,1),colors.lemonchiffon),

    ('GRID',(0,0),(-1,-1),0.5,colors.black),
    ('BOX',(0,0),(-1,-1),2,colors.black),

    ('LINEABOVE',(0,1),(10,1),2,colors.black),
    ('LINEABOVE',(0,2),(10,2),2,colors.black),
    ('LINEABOVE',(0,3),(10,3),2,colors.black),
]

# Footer styling (SAFE)
for r in range(footer_start, footer_end + 1):
    table_style.append(('SPAN', (0, r), (10, r)))
    table_style.append(('BACKGROUND', (0, r), (10, r), colors.lemonchiffon))

table_style.append(('LINEABOVE',(0, footer_start),(10, footer_start),2,colors.black))
t2 = Table(
    tdata,
    colWidths=colW,
    rowHeights=rowH,
    style=table_style
)
elements.append(t2)

fa,ax = plt.subplots(2,1,figsize=(7,9))
ax02 = ax[0].twinx()
ax12 = ax[1].twinx()

ax[0].plot(IW,'-o',color='blue')
ax[0].grid(True)
ax[0].set_xlabel("Time (AU)")
ax[0].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[0].set_title("SBCM-A 90% Fill Functional Test")
ax[0].tick_params(axis='y', labelcolor='blue')
ax02.plot(WAW,'-o',color='red')
ax02.plot(CAW,'-o',color='green')
ax02.plot(RAW,'-o',color='black')
ax02.set_ylabel("SBCM-A Status Bits",color='black')
ax02.set_yticks([0,1,2,3,4,5])
ax02.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT OFF: Beam="+str(round(WDTA90F[0],2))+"mA  SBCM="+str(round(WDTA90F[1],1))+"mV"
ax02.text(0.35, 0.96,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP OFF: Beam="+str(round(COMA90F[0],2))+"mA  SBCM="+str(round(COMA90F[1],1))+"mV"
ax02.text(0.35, 0.89,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELA90F[0]<50.0):
    line = "RELAY OFF: Beam="+str(round(RELA90F[0],2))+"mA  SBCM="+str(round(RELA90F[1],1))+"mV\n"
    line = line+"RELAY OFF Beam > 50.0 ? FAIL"
    ax02.text(0.35, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY OFF: Beam="+str(round(RELA90F[0],2))+"mA  SBCM="+str(round(RELA90F[1],1))+"mV\n"
    line = line+"RELAY OFF Beam > 50.0 ? PASS"
    ax02.text(0.35, 0.82,line,transform=ax02.transAxes,fontsize=10,verticalalignment='top', bbox=good)

ax[1].plot(IW,'-o',color='blue')
ax[1].grid(True)
ax[1].set_xlabel("Time (AU)")
ax[1].set_ylabel("EPS PLC DCCT Current (mA)",color='blue')
ax[1].tick_params(axis='y', labelcolor='blue')
ax12.plot(WBW,'-o',color='red')
ax12.plot(CBW,'-o',color='green')
ax12.plot(RBW,'-o',color='black')
ax12.set_ylabel("SBCM-B Status Bits",color='black')
ax[1].set_title("SBCM-B 90% Fill Functional Test")
ax12.set_yticks([0,1,2,3,4,5])
ax12.set_yticklabels(['OFF','WDT','COM','REL','',''])
line = "WDT OFF: Beam="+str(round(WDTB90F[0],2))+"mA  SBCM="+str(round(WDTB90F[1],1))+"mV"
ax12.text(0.35, 0.96,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
line = "COMP OFF: Beam="+str(round(COMB90F[0],2))+"mA  SBCM="+str(round(COMB90F[1],1))+"mV"
ax12.text(0.35, 0.89,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=props)
if(RELB90F[0]<50.0):
    line = "RELAY OFF: Beam="+str(round(RELB90F[0],2))+"mA  SBCM="+str(round(RELB90F[1],1))+"mV\n"
    line = line+"RELAY OFF Beam > 50.0 ? FAIL"
    ax12.text(0.35, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=bad)
else:
    line = "RELAY OFF: Beam="+str(round(RELB90F[0],2))+"mA  SBCM="+str(round(RELB90F[1],1))+"mV\n"
    line = line+"RELAY OFF Beam > 50.0 ? PASS"
    ax12.text(0.35, 0.82,line,transform=ax12.transAxes,fontsize=10,verticalalignment='top', bbox=good)

plt.tight_layout()
plt.pause(0.1)
plt.pause(0.1)
fa.savefig('SBCM_90pctFillBeamFallingFunctTest_'+year+'.png')
sleep(1)
elements.append(PageBreak())
im = Image('SBCM_90pctFillBeamFallingFunctTest_'+year+'.png',7*inch,8.5*inch)
elements.append(im)

tdata = []
tdata.append(["All Tests for this Procedure have PASSED"])
tdata.append(["TOSS SBCM Calibration Final Result:  PASS"])

ta=Table(tdata,6*inch,[0.32*inch,0.32*inch],style=[
                ('BACKGROUND',(0,0),(0,1),colors.palegreen),
                ('FONTSIZE',(0,0),(0,1),14),
                ('VALIGN',(0,0),(0,1),'MIDDLE'),
                ('GRID',(0,0),(-1,-1),1,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ])

elements.append(ta)
       
###############################################################################################
# End of Report...Building....
###############################################################################################
doc.build(elements)
